"""
Nihongo Quest - Hiragana Content Data
Complete hiragana character set with examples, organized by type.
Monument ID: 0 (The Hiragana Shrine)
"""

# =============================================================================
# BASIC HIRAGANA (46 characters)
# =============================================================================

HIRAGANA_BASIC = {
    "a": {
        "character": "\u3042",
        "romaji": "a",
        "row": "vowel",
        "example_word": "\u3042\u3081",
        "example_meaning": "rain",
    },
    "i": {
        "character": "\u3044",
        "romaji": "i",
        "row": "vowel",
        "example_word": "\u3044\u306c",
        "example_meaning": "dog",
    },
    "u": {
        "character": "\u3046",
        "romaji": "u",
        "row": "vowel",
        "example_word": "\u3046\u307f",
        "example_meaning": "sea",
    },
    "e": {
        "character": "\u3048",
        "romaji": "e",
        "row": "vowel",
        "example_word": "\u3048\u304d",
        "example_meaning": "station",
    },
    "o": {
        "character": "\u304a",
        "romaji": "o",
        "row": "vowel",
        "example_word": "\u304a\u3068",
        "example_meaning": "sound",
    },
    "ka": {
        "character": "\u304b",
        "romaji": "ka",
        "row": "k",
        "example_word": "\u304b\u305c",
        "example_meaning": "wind",
    },
    "ki": {
        "character": "\u304d",
        "romaji": "ki",
        "row": "k",
        "example_word": "\u304d\u305f",
        "example_meaning": "north",
    },
    "ku": {
        "character": "\u304f",
        "romaji": "ku",
        "row": "k",
        "example_word": "\u304f\u3082",
        "example_meaning": "cloud",
    },
    "ke": {
        "character": "\u3051",
        "romaji": "ke",
        "row": "k",
        "example_word": "\u3051\u3080\u308a",
        "example_meaning": "smoke",
    },
    "ko": {
        "character": "\u3053",
        "romaji": "ko",
        "row": "k",
        "example_word": "\u3053\u3048",
        "example_meaning": "voice",
    },
    "sa": {
        "character": "\u3055",
        "romaji": "sa",
        "row": "s",
        "example_word": "\u3055\u304f\u3089",
        "example_meaning": "cherry blossom",
    },
    "shi": {
        "character": "\u3057",
        "romaji": "shi",
        "row": "s",
        "example_word": "\u3057\u308d",
        "example_meaning": "white",
    },
    "su": {
        "character": "\u3059",
        "romaji": "su",
        "row": "s",
        "example_word": "\u3059\u3057",
        "example_meaning": "sushi",
    },
    "se": {
        "character": "\u305b",
        "romaji": "se",
        "row": "s",
        "example_word": "\u305b\u304b\u3044",
        "example_meaning": "world",
    },
    "so": {
        "character": "\u305d",
        "romaji": "so",
        "row": "s",
        "example_word": "\u305d\u3089",
        "example_meaning": "sky",
    },
    "ta": {
        "character": "\u305f",
        "romaji": "ta",
        "row": "t",
        "example_word": "\u305f\u307e\u3054",
        "example_meaning": "egg",
    },
    "chi": {
        "character": "\u3061",
        "romaji": "chi",
        "row": "t",
        "example_word": "\u3061\u304b\u3089",
        "example_meaning": "power",
    },
    "tsu": {
        "character": "\u3064",
        "romaji": "tsu",
        "row": "t",
        "example_word": "\u3064\u304d",
        "example_meaning": "moon",
    },
    "te": {
        "character": "\u3066",
        "romaji": "te",
        "row": "t",
        "example_word": "\u3066\u304c\u307f",
        "example_meaning": "letter",
    },
    "to": {
        "character": "\u3068",
        "romaji": "to",
        "row": "t",
        "example_word": "\u3068\u308a",
        "example_meaning": "bird",
    },
    "na": {
        "character": "\u306a",
        "romaji": "na",
        "row": "n",
        "example_word": "\u306a\u3064",
        "example_meaning": "summer",
    },
    "ni": {
        "character": "\u306b",
        "romaji": "ni",
        "row": "n",
        "example_word": "\u306b\u308f",
        "example_meaning": "garden",
    },
    "nu": {
        "character": "\u306c",
        "romaji": "nu",
        "row": "n",
        "example_word": "\u306c\u306e",
        "example_meaning": "cloth",
    },
    "ne": {
        "character": "\u306d",
        "romaji": "ne",
        "row": "n",
        "example_word": "\u306d\u3053",
        "example_meaning": "cat",
    },
    "no": {
        "character": "\u306e",
        "romaji": "no",
        "row": "n",
        "example_word": "\u306e\u308a",
        "example_meaning": "glue",
    },
    "ha": {
        "character": "\u306f",
        "romaji": "ha",
        "row": "h",
        "example_word": "\u306f\u306a",
        "example_meaning": "flower",
    },
    "hi": {
        "character": "\u3072",
        "romaji": "hi",
        "row": "h",
        "example_word": "\u3072\u304b\u308a",
        "example_meaning": "light",
    },
    "fu": {
        "character": "\u3075",
        "romaji": "fu",
        "row": "h",
        "example_word": "\u3075\u3086",
        "example_meaning": "winter",
    },
    "hu": {
        "character": "\u3075",
        "romaji": "fu",
        "row": "h",
        "example_word": "\u3075\u306d",
        "example_meaning": "ship",
    },
    "he": {
        "character": "\u3078",
        "romaji": "he",
        "row": "h",
        "example_word": "\u3078\u3084",
        "example_meaning": "room",
    },
    "ho": {
        "character": "\u307b",
        "romaji": "ho",
        "row": "h",
        "example_word": "\u307b\u3057",
        "example_meaning": "star",
    },
    "ma": {
        "character": "\u307e",
        "romaji": "ma",
        "row": "m",
        "example_word": "\u307e\u3061",
        "example_meaning": "town",
    },
    "mi": {
        "character": "\u307f",
        "romaji": "mi",
        "row": "m",
        "example_word": "\u307f\u305a",
        "example_meaning": "water",
    },
    "mu": {
        "character": "\u3080",
        "romaji": "mu",
        "row": "m",
        "example_word": "\u3080\u3057",
        "example_meaning": "insect",
    },
    "me": {
        "character": "\u3081",
        "romaji": "me",
        "row": "m",
        "example_word": "\u3081",
        "example_meaning": "eye",
    },
    "mo": {
        "character": "\u3082",
        "romaji": "mo",
        "row": "m",
        "example_word": "\u3082\u308a",
        "example_meaning": "forest",
    },
    "ya": {
        "character": "\u3084",
        "romaji": "ya",
        "row": "y",
        "example_word": "\u3084\u307e",
        "example_meaning": "mountain",
    },
    "yu": {
        "character": "\u3086",
        "romaji": "yu",
        "row": "y",
        "example_word": "\u3086\u304d",
        "example_meaning": "snow",
    },
    "yo": {
        "character": "\u3088",
        "romaji": "yo",
        "row": "y",
        "example_word": "\u3088\u308b",
        "example_meaning": "night",
    },
    "ra": {
        "character": "\u3089",
        "romaji": "ra",
        "row": "r",
        "example_word": "\u3089\u3044\u306d\u3093",
        "example_meaning": "next year",
    },
    "ri": {
        "character": "\u308a",
        "romaji": "ri",
        "row": "r",
        "example_word": "\u308a\u3093\u3054",
        "example_meaning": "apple",
    },
    "ru": {
        "character": "\u308b",
        "romaji": "ru",
        "row": "r",
        "example_word": "\u308b\u3059",
        "example_meaning": "to stay away",
    },
    "re": {
        "character": "\u308c",
        "romaji": "re",
        "row": "r",
        "example_word": "\u308c\u3044",
        "example_meaning": "example/manners",
    },
    "ro": {
        "character": "\u308d",
        "romaji": "ro",
        "row": "r",
        "example_word": "\u308d\u304f",
        "example_meaning": "six",
    },
    "wa": {
        "character": "\u308f",
        "romaji": "wa",
        "row": "w",
        "example_word": "\u308f\u305f\u3057",
        "example_meaning": "I/me",
    },
    "wo": {
        "character": "\u3092",
        "romaji": "wo",
        "row": "w",
        "example_word": "\u307f\u305a\u3092\u306e\u3080",
        "example_meaning": "to drink water",
    },
    "n": {
        "character": "\u3093",
        "romaji": "n",
        "row": "special",
        "example_word": "\u306b\u307b\u3093",
        "example_meaning": "Japan",
    },
}

# =============================================================================
# DAKUTEN HIRAGANA (voiced consonants)
# =============================================================================

HIRAGANA_DAKUTEN = {
    "ga": {
        "character": "\u304c",
        "romaji": "ga",
        "row": "g",
        "example_word": "\u304c\u3063\u3053\u3046",
        "example_meaning": "school",
    },
    "gi": {
        "character": "\u304e",
        "romaji": "gi",
        "row": "g",
        "example_word": "\u304e\u3093\u3053\u3046",
        "example_meaning": "bank",
    },
    "gu": {
        "character": "\u3050",
        "romaji": "gu",
        "row": "g",
        "example_word": "\u3050\u3042\u3044",
        "example_meaning": "by chance",
    },
    "ge": {
        "character": "\u3052",
        "romaji": "ge",
        "row": "g",
        "example_word": "\u3052\u3064\u3088\u3046\u3073",
        "example_meaning": "Monday",
    },
    "go": {
        "character": "\u3054",
        "romaji": "go",
        "row": "g",
        "example_word": "\u3054\u3054",
        "example_meaning": "afternoon",
    },
    "za": {
        "character": "\u3056",
        "romaji": "za",
        "row": "z",
        "example_word": "\u3056\u3063\u3057",
        "example_meaning": "magazine",
    },
    "ji": {
        "character": "\u3058",
        "romaji": "ji",
        "row": "z",
        "example_word": "\u3058\u304b\u3093",
        "example_meaning": "time",
    },
    "zu": {
        "character": "\u305a",
        "romaji": "zu",
        "row": "z",
        "example_word": "\u3059\u305a\u3057\u3044",
        "example_meaning": "cool (temperature)",
    },
    "ze": {
        "character": "\u305c",
        "romaji": "ze",
        "row": "z",
        "example_word": "\u305c\u3093\u3076",
        "example_meaning": "all",
    },
    "zo": {
        "character": "\u305e",
        "romaji": "zo",
        "row": "z",
        "example_word": "\u305e\u3046",
        "example_meaning": "elephant",
    },
    "da": {
        "character": "\u3060",
        "romaji": "da",
        "row": "d",
        "example_word": "\u3060\u3044\u304c\u304f",
        "example_meaning": "university",
    },
    "di": {
        "character": "\u3062",
        "romaji": "ji",
        "row": "d",
        "example_word": "\u3061\u3062\u307f",
        "example_meaning": "shrinking",
    },
    "du": {
        "character": "\u3065",
        "romaji": "zu",
        "row": "d",
        "example_word": "\u3064\u3065\u304f",
        "example_meaning": "to continue",
    },
    "de": {
        "character": "\u3067",
        "romaji": "de",
        "row": "d",
        "example_word": "\u3067\u3093\u308f",
        "example_meaning": "telephone",
    },
    "do": {
        "character": "\u3069",
        "romaji": "do",
        "row": "d",
        "example_word": "\u3069\u3046\u3076\u3064",
        "example_meaning": "animal",
    },
    "ba": {
        "character": "\u3070",
        "romaji": "ba",
        "row": "b",
        "example_word": "\u3070\u3057\u3087",
        "example_meaning": "place",
    },
    "bi": {
        "character": "\u3073",
        "romaji": "bi",
        "row": "b",
        "example_word": "\u3073\u3058\u3085\u3064\u304b\u3093",
        "example_meaning": "art museum",
    },
    "bu": {
        "character": "\u3076",
        "romaji": "bu",
        "row": "b",
        "example_word": "\u3076\u305f",
        "example_meaning": "pig",
    },
    "be": {
        "character": "\u3079",
        "romaji": "be",
        "row": "b",
        "example_word": "\u3079\u3093\u304d\u3087\u3046",
        "example_meaning": "study",
    },
    "bo": {
        "character": "\u307c",
        "romaji": "bo",
        "row": "b",
        "example_word": "\u307c\u3046\u3057",
        "example_meaning": "hat",
    },
}

# =============================================================================
# HANDAKUTEN HIRAGANA (p-sounds)
# =============================================================================

HIRAGANA_HANDAKUTEN = {
    "pa": {
        "character": "\u3071",
        "romaji": "pa",
        "row": "p",
        "example_word": "\u3071\u3093",
        "example_meaning": "bread",
    },
    "pi": {
        "character": "\u3074",
        "romaji": "pi",
        "row": "p",
        "example_word": "\u3074\u304b\u3074\u304b",
        "example_meaning": "shiny/sparkling",
    },
    "pu": {
        "character": "\u3077",
        "romaji": "pu",
        "row": "p",
        "example_word": "\u3066\u3093\u3077\u3089",
        "example_meaning": "tempura",
    },
    "pe": {
        "character": "\u307a",
        "romaji": "pe",
        "row": "p",
        "example_word": "\u307a\u3093",
        "example_meaning": "pen",
    },
    "po": {
        "character": "\u307d",
        "romaji": "po",
        "row": "p",
        "example_word": "\u3057\u3063\u307d",
        "example_meaning": "tail",
    },
}

# =============================================================================
# COMBINATION HIRAGANA (youon)
# =============================================================================

HIRAGANA_COMBOS = {
    "kya": {
        "character": "\u304d\u3083",
        "romaji": "kya",
        "row": "k-combo",
        "example_word": "\u304d\u3083\u304f",
        "example_meaning": "guest",
    },
    "kyu": {
        "character": "\u304d\u3085",
        "romaji": "kyu",
        "row": "k-combo",
        "example_word": "\u304d\u3085\u3046",
        "example_meaning": "nine",
    },
    "kyo": {
        "character": "\u304d\u3087",
        "romaji": "kyo",
        "row": "k-combo",
        "example_word": "\u304d\u3087\u3046",
        "example_meaning": "today",
    },
    "sha": {
        "character": "\u3057\u3083",
        "romaji": "sha",
        "row": "s-combo",
        "example_word": "\u3057\u3083\u3057\u3093",
        "example_meaning": "photograph",
    },
    "shu": {
        "character": "\u3057\u3085",
        "romaji": "shu",
        "row": "s-combo",
        "example_word": "\u3057\u3085\u304f\u3060\u3044",
        "example_meaning": "homework",
    },
    "sho": {
        "character": "\u3057\u3087",
        "romaji": "sho",
        "row": "s-combo",
        "example_word": "\u3057\u3087\u3046\u304c\u3064",
        "example_meaning": "New Year",
    },
    "cha": {
        "character": "\u3061\u3083",
        "romaji": "cha",
        "row": "t-combo",
        "example_word": "\u304a\u3061\u3083",
        "example_meaning": "tea",
    },
    "chu": {
        "character": "\u3061\u3085",
        "romaji": "chu",
        "row": "t-combo",
        "example_word": "\u3061\u3085\u3046\u3054\u304f",
        "example_meaning": "China",
    },
    "cho": {
        "character": "\u3061\u3087",
        "romaji": "cho",
        "row": "t-combo",
        "example_word": "\u3061\u3087\u3046\u3057\u3087\u304f",
        "example_meaning": "breakfast",
    },
    "nya": {
        "character": "\u306b\u3083",
        "romaji": "nya",
        "row": "n-combo",
        "example_word": "\u306b\u3083\u3093\u306b\u3083\u3093",
        "example_meaning": "meow meow (cat sound)",
    },
    "nyu": {
        "character": "\u306b\u3085",
        "romaji": "nyu",
        "row": "n-combo",
        "example_word": "\u306b\u3085\u3046\u304c\u304f",
        "example_meaning": "enrollment",
    },
    "nyo": {
        "character": "\u306b\u3087",
        "romaji": "nyo",
        "row": "n-combo",
        "example_word": "\u306b\u3087\u3046\u307c\u3046",
        "example_meaning": "urine",
    },
    "hya": {
        "character": "\u3072\u3083",
        "romaji": "hya",
        "row": "h-combo",
        "example_word": "\u3072\u3083\u304f",
        "example_meaning": "one hundred",
    },
    "hyu": {
        "character": "\u3072\u3085",
        "romaji": "hyu",
        "row": "h-combo",
        "example_word": "\u3072\u3085\u3046\u3072\u3085\u3046",
        "example_meaning": "whooshing sound (wind)",
    },
    "hyo": {
        "character": "\u3072\u3087",
        "romaji": "hyo",
        "row": "h-combo",
        "example_word": "\u3072\u3087\u3046",
        "example_meaning": "table/chart",
    },
    "mya": {
        "character": "\u307f\u3083",
        "romaji": "mya",
        "row": "m-combo",
        "example_word": "\u307f\u3083\u304f",
        "example_meaning": "pulse",
    },
    "myu": {
        "character": "\u307f\u3085",
        "romaji": "myu",
        "row": "m-combo",
        "example_word": "\u307f\u3085\u3046\u3058\u3063\u304f",
        "example_meaning": "music",
    },
    "myo": {
        "character": "\u307f\u3087",
        "romaji": "myo",
        "row": "m-combo",
        "example_word": "\u307f\u3087\u3046\u3058",
        "example_meaning": "strange",
    },
    "rya": {
        "character": "\u308a\u3083",
        "romaji": "rya",
        "row": "r-combo",
        "example_word": "\u308a\u3083\u304f\u3061\u3083",
        "example_meaning": "green tea",
    },
    "ryu": {
        "character": "\u308a\u3085",
        "romaji": "ryu",
        "row": "r-combo",
        "example_word": "\u308a\u3085\u3046\u304c\u304f",
        "example_meaning": "study abroad",
    },
    "ryo": {
        "character": "\u308a\u3087",
        "romaji": "ryo",
        "row": "r-combo",
        "example_word": "\u308a\u3087\u3046\u308a",
        "example_meaning": "cooking",
    },
    "gya": {
        "character": "\u304e\u3083",
        "romaji": "gya",
        "row": "g-combo",
        "example_word": "\u304e\u3083\u304f",
        "example_meaning": "reverse",
    },
    "gyu": {
        "character": "\u304e\u3085",
        "romaji": "gyu",
        "row": "g-combo",
        "example_word": "\u304e\u3085\u3046\u306b\u3085\u3046",
        "example_meaning": "milk",
    },
    "gyo": {
        "character": "\u304e\u3087",
        "romaji": "gyo",
        "row": "g-combo",
        "example_word": "\u304e\u3087\u3046\u3056",
        "example_meaning": "gyoza (dumplings)",
    },
    "ja": {
        "character": "\u3058\u3083",
        "romaji": "ja",
        "row": "z-combo",
        "example_word": "\u3058\u3083\u307e",
        "example_meaning": "hindrance",
    },
    "ju": {
        "character": "\u3058\u3085",
        "romaji": "ju",
        "row": "z-combo",
        "example_word": "\u3058\u3085\u3046\u3057\u3087",
        "example_meaning": "address",
    },
    "jo": {
        "character": "\u3058\u3087",
        "romaji": "jo",
        "row": "z-combo",
        "example_word": "\u3058\u3087\u3046\u305a",
        "example_meaning": "skillful",
    },
    "bya": {
        "character": "\u3073\u3083",
        "romaji": "bya",
        "row": "b-combo",
        "example_word": "\u3055\u3093\u3073\u3083\u304f",
        "example_meaning": "three hundred",
    },
    "byu": {
        "character": "\u3073\u3085",
        "romaji": "byu",
        "row": "b-combo",
        "example_word": "\u3073\u3085\u3046\u3073\u3085\u3046",
        "example_meaning": "whistling (wind sound)",
    },
    "byo": {
        "character": "\u3073\u3087",
        "romaji": "byo",
        "row": "b-combo",
        "example_word": "\u3073\u3087\u3046\u3044\u3093",
        "example_meaning": "hospital",
    },
    "pya": {
        "character": "\u3074\u3083",
        "romaji": "pya",
        "row": "p-combo",
        "example_word": "\u308d\u3063\u3074\u3083\u304f",
        "example_meaning": "six hundred",
    },
    "pyu": {
        "character": "\u3074\u3085",
        "romaji": "pyu",
        "row": "p-combo",
        "example_word": "\u3074\u3085\u3046\u3074\u3085\u3046",
        "example_meaning": "whooshing sound",
    },
    "pyo": {
        "character": "\u3074\u3087",
        "romaji": "pyo",
        "row": "p-combo",
        "example_word": "\u3074\u3087\u3093\u3074\u3087\u3093",
        "example_meaning": "hopping (onomatopoeia)",
    },
}

# =============================================================================
# HIRAGANA LESSONS
# =============================================================================

HIRAGANA_LESSONS = [
    {
        "lesson_id": "hira_01",
        "title": "The Five Vowels",
        "description": "Learn the foundation of Japanese: the five vowel sounds a, i, u, e, o.",
        "characters_taught": ["a", "i", "u", "e", "o"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_02",
        "title": "K-Row: Ka Ki Ku Ke Ko",
        "description": "Master the k-consonant row and form your first Japanese words.",
        "characters_taught": ["ka", "ki", "ku", "ke", "ko"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_03",
        "title": "S-Row: Sa Shi Su Se So",
        "description": "Learn the s-row. Note the irregular 'shi' instead of 'si'.",
        "characters_taught": ["sa", "shi", "su", "se", "so"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_04",
        "title": "T-Row: Ta Chi Tsu Te To",
        "description": "Master the t-row with its irregular characters 'chi' and 'tsu'.",
        "characters_taught": ["ta", "chi", "tsu", "te", "to"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_05",
        "title": "N-Row: Na Ni Nu Ne No",
        "description": "Learn the n-consonant row, one of the most regular rows.",
        "characters_taught": ["na", "ni", "nu", "ne", "no"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_06",
        "title": "H-Row: Ha Hi Fu He Ho",
        "description": "Master the h-row. Note 'fu' instead of 'hu' for the u-vowel pair.",
        "characters_taught": ["ha", "hi", "fu", "he", "ho"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_07",
        "title": "M-Row: Ma Mi Mu Me Mo",
        "description": "Learn the m-consonant row to expand your character repertoire.",
        "characters_taught": ["ma", "mi", "mu", "me", "mo"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_08",
        "title": "Y-Row and W-Row: Ya Yu Yo, Wa Wo, N",
        "description": "Complete basic hiragana with the y-row, w-row, and special 'n'.",
        "characters_taught": ["ya", "yu", "yo", "wa", "wo", "n"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_09",
        "title": "R-Row: Ra Ri Ru Re Ro",
        "description": "Master the r-row. The Japanese 'r' is between English 'r' and 'l'.",
        "characters_taught": ["ra", "ri", "ru", "re", "ro"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_10",
        "title": "Dakuten: Voiced Consonants",
        "description": "Add two small strokes to transform k->g, s->z, t->d, h->b.",
        "characters_taught": [
            "ga", "gi", "gu", "ge", "go",
            "za", "ji", "zu", "ze", "zo",
            "da", "di", "du", "de", "do",
            "ba", "bi", "bu", "be", "bo",
        ],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_11",
        "title": "Handakuten: P-Sounds",
        "description": "Add a small circle to h-row characters to create p-sounds.",
        "characters_taught": ["pa", "pi", "pu", "pe", "po"],
        "monument_id": 0,
    },
    {
        "lesson_id": "hira_12",
        "title": "Combination Characters (Youon)",
        "description": "Combine i-row characters with small ya, yu, yo to form new sounds.",
        "characters_taught": [
            "kya", "kyu", "kyo", "sha", "shu", "sho",
            "cha", "chu", "cho", "nya", "nyu", "nyo",
            "hya", "hyu", "hyo", "mya", "myu", "myo",
            "rya", "ryu", "ryo", "gya", "gyu", "gyo",
            "ja", "ju", "jo", "bya", "byu", "byo",
            "pya", "pyu", "pyo",
        ],
        "monument_id": 0,
    },
]
