"""
Nihongo Quest - Kanji Content Data
Japanese kanji characters organized by JLPT level.
Monument IDs: 5 (Kanji Castle N5), 8 (Kanji Keep N4)
"""

# =============================================================================
# JLPT N5 KANJI (~50 essential kanji)
# =============================================================================

KANJI_N5 = {
    "nichi": {
        "character": "日",
        "readings_on": ["ニチ", "ジツ"],
        "readings_kun": ["ひ", "か"],
        "meaning": "day, sun",
        "example_word": "日曜日",
        "example_reading": "にちようび",
        "example_meaning": "Sunday",
        "strokes": 4,
    },
    "getsu": {
        "character": "月",
        "readings_on": ["ゲツ", "ガツ"],
        "readings_kun": ["つき"],
        "meaning": "month, moon",
        "example_word": "月曜日",
        "example_reading": "げつようび",
        "example_meaning": "Monday",
        "strokes": 4,
    },
    "ka": {
        "character": "火",
        "readings_on": ["カ"],
        "readings_kun": ["ひ"],
        "meaning": "fire",
        "example_word": "火曜日",
        "example_reading": "かようび",
        "example_meaning": "Tuesday",
        "strokes": 4,
    },
    "sui": {
        "character": "水",
        "readings_on": ["スイ"],
        "readings_kun": ["みず"],
        "meaning": "water",
        "example_word": "水曜日",
        "example_reading": "すいようび",
        "example_meaning": "Wednesday",
        "strokes": 4,
    },
    "moku": {
        "character": "木",
        "readings_on": ["モク", "ボク"],
        "readings_kun": ["き", "こ"],
        "meaning": "tree, wood",
        "example_word": "木曜日",
        "example_reading": "もくようび",
        "example_meaning": "Thursday",
        "strokes": 4,
    },
    "kin": {
        "character": "金",
        "readings_on": ["キン", "コン"],
        "readings_kun": ["かね", "かな"],
        "meaning": "gold, money",
        "example_word": "金曜日",
        "example_reading": "きんようび",
        "example_meaning": "Friday",
        "strokes": 8,
    },
    "do": {
        "character": "土",
        "readings_on": ["ド", "ト"],
        "readings_kun": ["つち"],
        "meaning": "earth, soil",
        "example_word": "土曜日",
        "example_reading": "どようび",
        "example_meaning": "Saturday",
        "strokes": 3,
    },
    "ichi": {
        "character": "一",
        "readings_on": ["イチ", "イツ"],
        "readings_kun": ["ひと", "ひとつ"],
        "meaning": "one",
        "example_word": "一つ",
        "example_reading": "ひとつ",
        "example_meaning": "one (thing)",
        "strokes": 1,
    },
    "ni": {
        "character": "二",
        "readings_on": ["ニ"],
        "readings_kun": ["ふた", "ふたつ"],
        "meaning": "two",
        "example_word": "二つ",
        "example_reading": "ふたつ",
        "example_meaning": "two (things)",
        "strokes": 2,
    },
    "san": {
        "character": "三",
        "readings_on": ["サン"],
        "readings_kun": ["み", "みっつ"],
        "meaning": "three",
        "example_word": "三つ",
        "example_reading": "みっつ",
        "example_meaning": "three (things)",
        "strokes": 3,
    },
    "shi": {
        "character": "四",
        "readings_on": ["シ"],
        "readings_kun": ["よ", "よっつ", "よん"],
        "meaning": "four",
        "example_word": "四つ",
        "example_reading": "よっつ",
        "example_meaning": "four (things)",
        "strokes": 5,
    },
    "go": {
        "character": "五",
        "readings_on": ["ゴ"],
        "readings_kun": ["いつ", "いつつ"],
        "meaning": "five",
        "example_word": "五つ",
        "example_reading": "いつつ",
        "example_meaning": "five (things)",
        "strokes": 4,
    },
    "roku": {
        "character": "六",
        "readings_on": ["ロク"],
        "readings_kun": ["む", "むっつ", "むい"],
        "meaning": "six",
        "example_word": "六つ",
        "example_reading": "むっつ",
        "example_meaning": "six (things)",
        "strokes": 4,
    },
    "shichi": {
        "character": "七",
        "readings_on": ["シチ"],
        "readings_kun": ["なな", "ななつ", "なの"],
        "meaning": "seven",
        "example_word": "七つ",
        "example_reading": "ななつ",
        "example_meaning": "seven (things)",
        "strokes": 2,
    },
    "hachi": {
        "character": "八",
        "readings_on": ["ハチ"],
        "readings_kun": ["や", "やっつ", "よう"],
        "meaning": "eight",
        "example_word": "八つ",
        "example_reading": "やっつ",
        "example_meaning": "eight (things)",
        "strokes": 2,
    },
    "kyuu": {
        "character": "九",
        "readings_on": ["キュウ", "ク"],
        "readings_kun": ["ここの", "ここのつ"],
        "meaning": "nine",
        "example_word": "九つ",
        "example_reading": "ここのつ",
        "example_meaning": "nine (things)",
        "strokes": 2,
    },
    "juu": {
        "character": "十",
        "readings_on": ["ジュウ", "ジッ"],
        "readings_kun": ["とお", "と"],
        "meaning": "ten",
        "example_word": "十日",
        "example_reading": "とおか",
        "example_meaning": "tenth day",
        "strokes": 2,
    },
    "hyaku": {
        "character": "百",
        "readings_on": ["ヒャク"],
        "readings_kun": [],
        "meaning": "hundred",
        "example_word": "百円",
        "example_reading": "ひゃくえん",
        "example_meaning": "one hundred yen",
        "strokes": 6,
    },
    "sen": {
        "character": "千",
        "readings_on": ["セン"],
        "readings_kun": ["ち"],
        "meaning": "thousand",
        "example_word": "千円",
        "example_reading": "せんえん",
        "example_meaning": "one thousand yen",
        "strokes": 3,
    },
    "man": {
        "character": "万",
        "readings_on": ["マン", "バン"],
        "readings_kun": [],
        "meaning": "ten thousand",
        "example_word": "一万円",
        "example_reading": "いちまんえん",
        "example_meaning": "ten thousand yen",
        "strokes": 3,
    },
    "jin": {
        "character": "人",
        "readings_on": ["ジン", "ニン"],
        "readings_kun": ["ひと"],
        "meaning": "person, people",
        "example_word": "日本人",
        "example_reading": "にほんじん",
        "example_meaning": "Japanese person",
        "strokes": 2,
    },
    "dai": {
        "character": "大",
        "readings_on": ["ダイ", "タイ"],
        "readings_kun": ["おお", "おおきい"],
        "meaning": "big, large",
        "example_word": "大きい",
        "example_reading": "おおきい",
        "example_meaning": "big",
        "strokes": 3,
    },
    "shou": {
        "character": "小",
        "readings_on": ["ショウ"],
        "readings_kun": ["ちい", "ちいさい", "こ", "お"],
        "meaning": "small, little",
        "example_word": "小さい",
        "example_reading": "ちいさい",
        "example_meaning": "small",
        "strokes": 3,
    },
    "jou": {
        "character": "上",
        "readings_on": ["ジョウ"],
        "readings_kun": ["うえ", "あ", "のぼ", "かみ"],
        "meaning": "above, up",
        "example_word": "上げる",
        "example_reading": "あげる",
        "example_meaning": "to raise",
        "strokes": 3,
    },
    "ka_shita": {
        "character": "下",
        "readings_on": ["カ", "ゲ"],
        "readings_kun": ["した", "さ", "くだ", "お"],
        "meaning": "below, down",
        "example_word": "下さい",
        "example_reading": "ください",
        "example_meaning": "please give me",
        "strokes": 3,
    },
    "chuu": {
        "character": "中",
        "readings_on": ["チュウ"],
        "readings_kun": ["なか"],
        "meaning": "middle, inside",
        "example_word": "中学校",
        "example_reading": "ちゅうがっこう",
        "example_meaning": "middle school",
        "strokes": 4,
    },
    "san_yama": {
        "character": "山",
        "readings_on": ["サン"],
        "readings_kun": ["やま"],
        "meaning": "mountain",
        "example_word": "富士山",
        "example_reading": "ふじさん",
        "example_meaning": "Mount Fuji",
        "strokes": 3,
    },
    "sen_kawa": {
        "character": "川",
        "readings_on": ["セン"],
        "readings_kun": ["かわ"],
        "meaning": "river",
        "example_word": "川",
        "example_reading": "かわ",
        "example_meaning": "river",
        "strokes": 3,
    },
    "kou_kuchi": {
        "character": "口",
        "readings_on": ["コウ", "ク"],
        "readings_kun": ["くち"],
        "meaning": "mouth, opening",
        "example_word": "入口",
        "example_reading": "いりぐち",
        "example_meaning": "entrance",
        "strokes": 3,
    },
    "moku_me": {
        "character": "目",
        "readings_on": ["モク", "ボク"],
        "readings_kun": ["め"],
        "meaning": "eye",
        "example_word": "目",
        "example_reading": "め",
        "example_meaning": "eye",
        "strokes": 5,
    },
    "shu_te": {
        "character": "手",
        "readings_on": ["シュ"],
        "readings_kun": ["て"],
        "meaning": "hand",
        "example_word": "上手",
        "example_reading": "じょうず",
        "example_meaning": "skillful",
        "strokes": 4,
    },
    "soku_ashi": {
        "character": "足",
        "readings_on": ["ソク"],
        "readings_kun": ["あし", "た"],
        "meaning": "foot, leg, sufficient",
        "example_word": "足りる",
        "example_reading": "たりる",
        "example_meaning": "to be sufficient",
        "strokes": 7,
    },
    "ji_mimi": {
        "character": "耳",
        "readings_on": ["ジ"],
        "readings_kun": ["みみ"],
        "meaning": "ear",
        "example_word": "耳",
        "example_reading": "みみ",
        "example_meaning": "ear",
        "strokes": 6,
    },
    "haku_shiro": {
        "character": "白",
        "readings_on": ["ハク", "ビャク"],
        "readings_kun": ["しろ", "しろい"],
        "meaning": "white",
        "example_word": "白い",
        "example_reading": "しろい",
        "example_meaning": "white",
        "strokes": 5,
    },
    "seki_aka": {
        "character": "赤",
        "readings_on": ["セキ", "シャク"],
        "readings_kun": ["あか", "あかい"],
        "meaning": "red",
        "example_word": "赤い",
        "example_reading": "あかい",
        "example_meaning": "red",
        "strokes": 7,
    },
    "sei_ao": {
        "character": "青",
        "readings_on": ["セイ", "ショウ"],
        "readings_kun": ["あお", "あおい"],
        "meaning": "blue, green",
        "example_word": "青い",
        "example_reading": "あおい",
        "example_meaning": "blue",
        "strokes": 8,
    },
    "sha_kuruma": {
        "character": "車",
        "readings_on": ["シャ"],
        "readings_kun": ["くるま"],
        "meaning": "car, vehicle",
        "example_word": "電車",
        "example_reading": "でんしゃ",
        "example_meaning": "train",
        "strokes": 7,
    },
    "gaku": {
        "character": "学",
        "readings_on": ["ガク"],
        "readings_kun": ["まな"],
        "meaning": "study, learning",
        "example_word": "学生",
        "example_reading": "がくせい",
        "example_meaning": "student",
        "strokes": 8,
    },
    "kou_school": {
        "character": "校",
        "readings_on": ["コウ"],
        "readings_kun": [],
        "meaning": "school",
        "example_word": "学校",
        "example_reading": "がっこう",
        "example_meaning": "school",
        "strokes": 10,
    },
    "sen_saki": {
        "character": "先",
        "readings_on": ["セン"],
        "readings_kun": ["さき"],
        "meaning": "previous, ahead",
        "example_word": "先生",
        "example_reading": "せんせい",
        "example_meaning": "teacher",
        "strokes": 6,
    },
    "sei_life": {
        "character": "生",
        "readings_on": ["セイ", "ショウ"],
        "readings_kun": ["い", "う", "は", "なま"],
        "meaning": "life, birth, raw",
        "example_word": "学生",
        "example_reading": "がくせい",
        "example_meaning": "student",
        "strokes": 5,
    },
    "shoku_taberu": {
        "character": "食",
        "readings_on": ["ショク", "ジキ"],
        "readings_kun": ["た", "く"],
        "meaning": "eat, food",
        "example_word": "食べる",
        "example_reading": "たべる",
        "example_meaning": "to eat",
        "strokes": 9,
    },
    "in_nomu": {
        "character": "飲",
        "readings_on": ["イン"],
        "readings_kun": ["の"],
        "meaning": "drink",
        "example_word": "飲む",
        "example_reading": "のむ",
        "example_meaning": "to drink",
        "strokes": 12,
    },
    "ken_miru": {
        "character": "見",
        "readings_on": ["ケン"],
        "readings_kun": ["み"],
        "meaning": "see, look",
        "example_word": "見る",
        "example_reading": "みる",
        "example_meaning": "to see",
        "strokes": 7,
    },
    "bun_kiku": {
        "character": "聞",
        "readings_on": ["ブン", "モン"],
        "readings_kun": ["き"],
        "meaning": "hear, ask, listen",
        "example_word": "聞く",
        "example_reading": "きく",
        "example_meaning": "to listen",
        "strokes": 14,
    },
    "doku_yomu": {
        "character": "読",
        "readings_on": ["ドク", "トク", "トウ"],
        "readings_kun": ["よ"],
        "meaning": "read",
        "example_word": "読む",
        "example_reading": "よむ",
        "example_meaning": "to read",
        "strokes": 14,
    },
    "sho_kaku": {
        "character": "書",
        "readings_on": ["ショ"],
        "readings_kun": ["か"],
        "meaning": "write",
        "example_word": "書く",
        "example_reading": "かく",
        "example_meaning": "to write",
        "strokes": 10,
    },
    "wa_hanasu": {
        "character": "話",
        "readings_on": ["ワ"],
        "readings_kun": ["はなし", "はな"],
        "meaning": "talk, story",
        "example_word": "電話",
        "example_reading": "でんわ",
        "example_meaning": "telephone",
        "strokes": 13,
    },
    "kou_iku": {
        "character": "行",
        "readings_on": ["コウ", "ギョウ"],
        "readings_kun": ["い", "ゆ", "おこな"],
        "meaning": "go, carry out",
        "example_word": "行く",
        "example_reading": "いく",
        "example_meaning": "to go",
        "strokes": 6,
    },
    "rai_kuru": {
        "character": "来",
        "readings_on": ["ライ"],
        "readings_kun": ["く", "き", "きた"],
        "meaning": "come, next",
        "example_word": "来る",
        "example_reading": "くる",
        "example_meaning": "to come",
        "strokes": 7,
    },
    "shutsu_deru": {
        "character": "出",
        "readings_on": ["シュツ", "スイ"],
        "readings_kun": ["で", "だ"],
        "meaning": "exit, leave, put out",
        "example_word": "出る",
        "example_reading": "でる",
        "example_meaning": "to go out",
        "strokes": 5,
    },
}

# =============================================================================
# INTERMEDIATE KANJI (~30 N4-level kanji)
# =============================================================================

KANJI_INTERMEDIATE = {
    "ka_ie": {
        "character": "家",
        "readings_on": ["カ", "ケ"],
        "readings_kun": ["いえ", "や"],
        "meaning": "house, home, family",
        "example_word": "家族",
        "example_reading": "かぞく",
        "example_meaning": "family",
        "strokes": 10,
    },
    "ten_mise": {
        "character": "店",
        "readings_on": ["テン"],
        "readings_kun": ["みせ"],
        "meaning": "shop, store",
        "example_word": "喫茶店",
        "example_reading": "きっさてん",
        "example_meaning": "cafe",
        "strokes": 8,
    },
    "dou_michi": {
        "character": "道",
        "readings_on": ["ドウ", "トウ"],
        "readings_kun": ["みち"],
        "meaning": "road, path, way",
        "example_word": "道路",
        "example_reading": "どうろ",
        "example_meaning": "road",
        "strokes": 12,
    },
    "eki": {
        "character": "駅",
        "readings_on": ["エキ"],
        "readings_kun": [],
        "meaning": "station",
        "example_word": "東京駅",
        "example_reading": "とうきょうえき",
        "example_meaning": "Tokyo Station",
        "strokes": 14,
    },
    "den": {
        "character": "電",
        "readings_on": ["デン"],
        "readings_kun": [],
        "meaning": "electricity",
        "example_word": "電気",
        "example_reading": "でんき",
        "example_meaning": "electricity, light",
        "strokes": 13,
    },
    "wa_hanashi": {
        "character": "話",
        "readings_on": ["ワ"],
        "readings_kun": ["はなし", "はな"],
        "meaning": "talk, story",
        "example_word": "会話",
        "example_reading": "かいわ",
        "example_meaning": "conversation",
        "strokes": 13,
    },
    "go_language": {
        "character": "語",
        "readings_on": ["ゴ"],
        "readings_kun": ["かた"],
        "meaning": "language, word",
        "example_word": "日本語",
        "example_reading": "にほんご",
        "example_meaning": "Japanese language",
        "strokes": 14,
    },
    "koku_kuni": {
        "character": "国",
        "readings_on": ["コク"],
        "readings_kun": ["くに"],
        "meaning": "country",
        "example_word": "外国",
        "example_reading": "がいこく",
        "example_meaning": "foreign country",
        "strokes": 8,
    },
    "gai_soto": {
        "character": "外",
        "readings_on": ["ガイ", "ゲ"],
        "readings_kun": ["そと", "ほか", "はず"],
        "meaning": "outside, foreign",
        "example_word": "外国人",
        "example_reading": "がいこくじん",
        "example_meaning": "foreigner",
        "strokes": 5,
    },
    "kai_au": {
        "character": "会",
        "readings_on": ["カイ", "エ"],
        "readings_kun": ["あ"],
        "meaning": "meet, association",
        "example_word": "会社",
        "example_reading": "かいしゃ",
        "example_meaning": "company",
        "strokes": 6,
    },
    "sha_yashiro": {
        "character": "社",
        "readings_on": ["シャ"],
        "readings_kun": ["やしろ"],
        "meaning": "company, shrine",
        "example_word": "神社",
        "example_reading": "じんじゃ",
        "example_meaning": "shrine",
        "strokes": 7,
    },
    "kon_ima": {
        "character": "今",
        "readings_on": ["コン", "キン"],
        "readings_kun": ["いま"],
        "meaning": "now, this",
        "example_word": "今日",
        "example_reading": "きょう",
        "example_meaning": "today",
        "strokes": 4,
    },
    "nen_toshi": {
        "character": "年",
        "readings_on": ["ネン"],
        "readings_kun": ["とし"],
        "meaning": "year",
        "example_word": "今年",
        "example_reading": "ことし",
        "example_meaning": "this year",
        "strokes": 6,
    },
    "ji_toki": {
        "character": "時",
        "readings_on": ["ジ"],
        "readings_kun": ["とき"],
        "meaning": "time, hour",
        "example_word": "時間",
        "example_reading": "じかん",
        "example_meaning": "time, hour",
        "strokes": 10,
    },
    "kan_aida": {
        "character": "間",
        "readings_on": ["カン", "ケン"],
        "readings_kun": ["あいだ", "ま"],
        "meaning": "interval, between",
        "example_word": "時間",
        "example_reading": "じかん",
        "example_meaning": "time, hour",
        "strokes": 12,
    },
    "bun_fun": {
        "character": "分",
        "readings_on": ["ブン", "フン", "ブ"],
        "readings_kun": ["わ"],
        "meaning": "minute, part, divide",
        "example_word": "十分",
        "example_reading": "じゅっぷん",
        "example_meaning": "ten minutes",
        "strokes": 4,
    },
    "han": {
        "character": "半",
        "readings_on": ["ハン"],
        "readings_kun": ["なか"],
        "meaning": "half",
        "example_word": "半分",
        "example_reading": "はんぶん",
        "example_meaning": "half",
        "strokes": 5,
    },
    "zen_mae": {
        "character": "前",
        "readings_on": ["ゼン"],
        "readings_kun": ["まえ"],
        "meaning": "before, front",
        "example_word": "名前",
        "example_reading": "なまえ",
        "example_meaning": "name",
        "strokes": 9,
    },
    "go_ato": {
        "character": "後",
        "readings_on": ["ゴ", "コウ"],
        "readings_kun": ["あと", "うし", "のち"],
        "meaning": "after, behind",
        "example_word": "午後",
        "example_reading": "ごご",
        "example_meaning": "afternoon",
        "strokes": 9,
    },
    "hoku_kita": {
        "character": "北",
        "readings_on": ["ホク"],
        "readings_kun": ["きた"],
        "meaning": "north",
        "example_word": "北海道",
        "example_reading": "ほっかいどう",
        "example_meaning": "Hokkaido",
        "strokes": 5,
    },
    "nan_minami": {
        "character": "南",
        "readings_on": ["ナン", "ナ"],
        "readings_kun": ["みなみ"],
        "meaning": "south",
        "example_word": "南口",
        "example_reading": "みなみぐち",
        "example_meaning": "south exit",
        "strokes": 9,
    },
    "tou_higashi": {
        "character": "東",
        "readings_on": ["トウ"],
        "readings_kun": ["ひがし"],
        "meaning": "east",
        "example_word": "東京",
        "example_reading": "とうきょう",
        "example_meaning": "Tokyo",
        "strokes": 8,
    },
    "sei_nishi": {
        "character": "西",
        "readings_on": ["セイ", "サイ"],
        "readings_kun": ["にし"],
        "meaning": "west",
        "example_word": "西口",
        "example_reading": "にしぐち",
        "example_meaning": "west exit",
        "strokes": 6,
    },
    "ten_ame": {
        "character": "天",
        "readings_on": ["テン"],
        "readings_kun": ["あめ", "あま"],
        "meaning": "heaven, sky",
        "example_word": "天気",
        "example_reading": "てんき",
        "example_meaning": "weather",
        "strokes": 4,
    },
    "ki_spirit": {
        "character": "気",
        "readings_on": ["キ", "ケ"],
        "readings_kun": [],
        "meaning": "spirit, energy, air",
        "example_word": "元気",
        "example_reading": "げんき",
        "example_meaning": "healthy, energetic",
        "strokes": 6,
    },
    "u_ame": {
        "character": "雨",
        "readings_on": ["ウ"],
        "readings_kun": ["あめ", "あま"],
        "meaning": "rain",
        "example_word": "大雨",
        "example_reading": "おおあめ",
        "example_meaning": "heavy rain",
        "strokes": 8,
    },
    "setsu_yuki": {
        "character": "雪",
        "readings_on": ["セツ"],
        "readings_kun": ["ゆき"],
        "meaning": "snow",
        "example_word": "大雪",
        "example_reading": "おおゆき",
        "example_meaning": "heavy snow",
        "strokes": 11,
    },
    "fuu_kaze": {
        "character": "風",
        "readings_on": ["フウ", "フ"],
        "readings_kun": ["かぜ", "かざ"],
        "meaning": "wind, style",
        "example_word": "台風",
        "example_reading": "たいふう",
        "example_meaning": "typhoon",
        "strokes": 9,
    },
    "ka_hana": {
        "character": "花",
        "readings_on": ["カ"],
        "readings_kun": ["はな"],
        "meaning": "flower",
        "example_word": "花見",
        "example_reading": "はなみ",
        "example_meaning": "cherry blossom viewing",
        "strokes": 7,
    },
    "shun_haru": {
        "character": "春",
        "readings_on": ["シュン"],
        "readings_kun": ["はる"],
        "meaning": "spring (season)",
        "example_word": "春休み",
        "example_reading": "はるやすみ",
        "example_meaning": "spring break",
        "strokes": 9,
    },
}

# =============================================================================
# KANJI LESSONS
# =============================================================================

KANJI_LESSONS = [
    # --- Monument 5: Kanji Castle N5 (6 lessons) ---
    {
        "lesson_id": "kanji_01",
        "title": "Days of the Week Kanji",
        "description": "Learn the seven kanji used in the days of the week, representing the classical elements.",
        "characters_taught": ["日", "月", "火", "水", "木", "金", "土"],
        "monument_id": 5,
    },
    {
        "lesson_id": "kanji_02",
        "title": "Numbers: One through Ten",
        "description": "Master the kanji for numbers one through ten, the foundation of counting in Japanese.",
        "characters_taught": ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十"],
        "monument_id": 5,
    },
    {
        "lesson_id": "kanji_03",
        "title": "Large Numbers and People",
        "description": "Learn kanji for large numbers and the essential kanji for person.",
        "characters_taught": ["百", "千", "万", "人"],
        "monument_id": 5,
    },
    {
        "lesson_id": "kanji_04",
        "title": "Size, Position, and Nature",
        "description": "Kanji for describing size, spatial positions, and features of the natural world.",
        "characters_taught": ["大", "小", "上", "下", "中", "山", "川"],
        "monument_id": 5,
    },
    {
        "lesson_id": "kanji_05",
        "title": "Body, Colors, and Vehicles",
        "description": "Learn kanji for body parts, basic colors, and transportation.",
        "characters_taught": ["口", "目", "手", "足", "耳", "白", "赤", "青", "車"],
        "monument_id": 5,
    },
    {
        "lesson_id": "kanji_06",
        "title": "School and Action Verbs",
        "description": "Essential kanji for school life and common action verbs like eat, drink, read, and write.",
        "characters_taught": ["学", "校", "先", "生", "食", "飲", "見", "聞", "読", "書", "話", "行", "来", "出"],
        "monument_id": 5,
    },
    # --- Monument 8: Kanji Keep N4 (4 lessons) ---
    {
        "lesson_id": "kanji_07",
        "title": "Places and Society",
        "description": "Kanji for buildings, places, and social structures found in everyday life.",
        "characters_taught": ["家", "店", "道", "駅", "電", "話", "語", "国", "外", "会", "社"],
        "monument_id": 8,
    },
    {
        "lesson_id": "kanji_08",
        "title": "Time and Sequence",
        "description": "Master kanji for expressing time, duration, and temporal relationships.",
        "characters_taught": ["今", "年", "時", "間", "分", "半", "前", "後"],
        "monument_id": 8,
    },
    {
        "lesson_id": "kanji_09",
        "title": "Directions and Navigation",
        "description": "Learn the four cardinal direction kanji and the kanji for heaven.",
        "characters_taught": ["北", "南", "東", "西", "天"],
        "monument_id": 8,
    },
    {
        "lesson_id": "kanji_10",
        "title": "Weather, Nature, and Seasons",
        "description": "Kanji for weather phenomena, natural elements, and the beauty of the seasons.",
        "characters_taught": ["気", "雨", "雪", "風", "花", "春"],
        "monument_id": 8,
    },
]
