"""
Nihongo Quest - Katakana Content Data
Complete katakana character set with foreign loanword examples, organized by type.
Monument ID: 1 (The Katakana Fortress)
"""

# =============================================================================
# BASIC KATAKANA (46 characters)
# =============================================================================

KATAKANA_BASIC = {
    "a": {
        "character": "\u30a2",
        "romaji": "a",
        "row": "vowel",
        "example_word": "\u30a2\u30e1\u30ea\u30ab",
        "example_meaning": "America",
    },
    "i": {
        "character": "\u30a4",
        "romaji": "i",
        "row": "vowel",
        "example_word": "\u30a4\u30ae\u30ea\u30b9",
        "example_meaning": "England",
    },
    "u": {
        "character": "\u30a6",
        "romaji": "u",
        "row": "vowel",
        "example_word": "\u30a6\u30a9\u30fc\u30bf\u30fc",
        "example_meaning": "water (from English 'water')",
    },
    "e": {
        "character": "\u30a8",
        "romaji": "e",
        "row": "vowel",
        "example_word": "\u30a8\u30cd\u30eb\u30ae\u30fc",
        "example_meaning": "energy",
    },
    "o": {
        "character": "\u30aa",
        "romaji": "o",
        "row": "vowel",
        "example_word": "\u30aa\u30ec\u30f3\u30b8",
        "example_meaning": "orange",
    },
    "ka": {
        "character": "\u30ab",
        "romaji": "ka",
        "row": "k",
        "example_word": "\u30ab\u30e1\u30e9",
        "example_meaning": "camera",
    },
    "ki": {
        "character": "\u30ad",
        "romaji": "ki",
        "row": "k",
        "example_word": "\u30ad\u30c3\u30c1\u30f3",
        "example_meaning": "kitchen",
    },
    "ku": {
        "character": "\u30af",
        "romaji": "ku",
        "row": "k",
        "example_word": "\u30af\u30e9\u30b9",
        "example_meaning": "class",
    },
    "ke": {
        "character": "\u30b1",
        "romaji": "ke",
        "row": "k",
        "example_word": "\u30b1\u30fc\u30ad",
        "example_meaning": "cake",
    },
    "ko": {
        "character": "\u30b3",
        "romaji": "ko",
        "row": "k",
        "example_word": "\u30b3\u30fc\u30d2\u30fc",
        "example_meaning": "coffee",
    },
    "sa": {
        "character": "\u30b5",
        "romaji": "sa",
        "row": "s",
        "example_word": "\u30b5\u30e9\u30c0",
        "example_meaning": "salad",
    },
    "shi": {
        "character": "\u30b7",
        "romaji": "shi",
        "row": "s",
        "example_word": "\u30b7\u30e3\u30c4",
        "example_meaning": "shirt",
    },
    "su": {
        "character": "\u30b9",
        "romaji": "su",
        "row": "s",
        "example_word": "\u30b9\u30dd\u30fc\u30c4",
        "example_meaning": "sports",
    },
    "se": {
        "character": "\u30bb",
        "romaji": "se",
        "row": "s",
        "example_word": "\u30bb\u30fc\u30bf\u30fc",
        "example_meaning": "sweater",
    },
    "so": {
        "character": "\u30bd",
        "romaji": "so",
        "row": "s",
        "example_word": "\u30bd\u30d5\u30a1\u30fc",
        "example_meaning": "sofa",
    },
    "ta": {
        "character": "\u30bf",
        "romaji": "ta",
        "row": "t",
        "example_word": "\u30bf\u30af\u30b7\u30fc",
        "example_meaning": "taxi",
    },
    "chi": {
        "character": "\u30c1",
        "romaji": "chi",
        "row": "t",
        "example_word": "\u30c1\u30fc\u30ba",
        "example_meaning": "cheese",
    },
    "tsu": {
        "character": "\u30c4",
        "romaji": "tsu",
        "row": "t",
        "example_word": "\u30c4\u30a2\u30fc",
        "example_meaning": "tour",
    },
    "te": {
        "character": "\u30c6",
        "romaji": "te",
        "row": "t",
        "example_word": "\u30c6\u30b9\u30c8",
        "example_meaning": "test",
    },
    "to": {
        "character": "\u30c8",
        "romaji": "to",
        "row": "t",
        "example_word": "\u30c8\u30a4\u30ec",
        "example_meaning": "toilet",
    },
    "na": {
        "character": "\u30ca",
        "romaji": "na",
        "row": "n",
        "example_word": "\u30ca\u30a4\u30d5",
        "example_meaning": "knife",
    },
    "ni": {
        "character": "\u30cb",
        "romaji": "ni",
        "row": "n",
        "example_word": "\u30cb\u30e5\u30fc\u30b9",
        "example_meaning": "news",
    },
    "nu": {
        "character": "\u30cc",
        "romaji": "nu",
        "row": "n",
        "example_word": "\u30cc\u30fc\u30c9\u30eb",
        "example_meaning": "noodle",
    },
    "ne": {
        "character": "\u30cd",
        "romaji": "ne",
        "row": "n",
        "example_word": "\u30cd\u30af\u30bf\u30a4",
        "example_meaning": "necktie",
    },
    "no": {
        "character": "\u30ce",
        "romaji": "no",
        "row": "n",
        "example_word": "\u30ce\u30fc\u30c8",
        "example_meaning": "notebook",
    },
    "ha": {
        "character": "\u30cf",
        "romaji": "ha",
        "row": "h",
        "example_word": "\u30cf\u30f3\u30d0\u30fc\u30ac\u30fc",
        "example_meaning": "hamburger",
    },
    "hi": {
        "character": "\u30d2",
        "romaji": "hi",
        "row": "h",
        "example_word": "\u30d2\u30fc\u30bf\u30fc",
        "example_meaning": "heater",
    },
    "fu": {
        "character": "\u30d5",
        "romaji": "fu",
        "row": "h",
        "example_word": "\u30d5\u30e9\u30f3\u30b9",
        "example_meaning": "France",
    },
    "hu": {
        "character": "\u30d5",
        "romaji": "fu",
        "row": "h",
        "example_word": "\u30d5\u30a9\u30fc\u30af",
        "example_meaning": "fork",
    },
    "he": {
        "character": "\u30d8",
        "romaji": "he",
        "row": "h",
        "example_word": "\u30d8\u30eb\u30e1\u30c3\u30c8",
        "example_meaning": "helmet",
    },
    "ho": {
        "character": "\u30db",
        "romaji": "ho",
        "row": "h",
        "example_word": "\u30db\u30c6\u30eb",
        "example_meaning": "hotel",
    },
    "ma": {
        "character": "\u30de",
        "romaji": "ma",
        "row": "m",
        "example_word": "\u30de\u30f3\u30b7\u30e7\u30f3",
        "example_meaning": "apartment building",
    },
    "mi": {
        "character": "\u30df",
        "romaji": "mi",
        "row": "m",
        "example_word": "\u30df\u30eb\u30af",
        "example_meaning": "milk",
    },
    "mu": {
        "character": "\u30e0",
        "romaji": "mu",
        "row": "m",
        "example_word": "\u30e0\u30fc\u30d3\u30fc",
        "example_meaning": "movie (from English 'movie')",
    },
    "me": {
        "character": "\u30e1",
        "romaji": "me",
        "row": "m",
        "example_word": "\u30e1\u30cb\u30e5\u30fc",
        "example_meaning": "menu",
    },
    "mo": {
        "character": "\u30e2",
        "romaji": "mo",
        "row": "m",
        "example_word": "\u30e2\u30c7\u30eb",
        "example_meaning": "model",
    },
    "ya": {
        "character": "\u30e4",
        "romaji": "ya",
        "row": "y",
        "example_word": "\u30e4\u30f3\u30ad\u30fc\u30b9\u30bf\u30b8\u30a2\u30e0",
        "example_meaning": "Yankee Stadium",
    },
    "yu": {
        "character": "\u30e6",
        "romaji": "yu",
        "row": "y",
        "example_word": "\u30e6\u30cb\u30d5\u30a9\u30fc\u30e0",
        "example_meaning": "uniform",
    },
    "yo": {
        "character": "\u30e8",
        "romaji": "yo",
        "row": "y",
        "example_word": "\u30e8\u30fc\u30ed\u30c3\u30d1",
        "example_meaning": "Europe",
    },
    "ra": {
        "character": "\u30e9",
        "romaji": "ra",
        "row": "r",
        "example_word": "\u30e9\u30b8\u30aa",
        "example_meaning": "radio",
    },
    "ri": {
        "character": "\u30ea",
        "romaji": "ri",
        "row": "r",
        "example_word": "\u30ea\u30b9\u30c8",
        "example_meaning": "list",
    },
    "ru": {
        "character": "\u30eb",
        "romaji": "ru",
        "row": "r",
        "example_word": "\u30eb\u30fc\u30eb",
        "example_meaning": "rule",
    },
    "re": {
        "character": "\u30ec",
        "romaji": "re",
        "row": "r",
        "example_word": "\u30ec\u30b9\u30c8\u30e9\u30f3",
        "example_meaning": "restaurant",
    },
    "ro": {
        "character": "\u30ed",
        "romaji": "ro",
        "row": "r",
        "example_word": "\u30ed\u30dc\u30c3\u30c8",
        "example_meaning": "robot",
    },
    "wa": {
        "character": "\u30ef",
        "romaji": "wa",
        "row": "w",
        "example_word": "\u30ef\u30a4\u30f3",
        "example_meaning": "wine",
    },
    "wo": {
        "character": "\u30f2",
        "romaji": "wo",
        "row": "w",
        "example_word": "\u30f2",
        "example_meaning": "(particle, rarely used in katakana)",
    },
    "n": {
        "character": "\u30f3",
        "romaji": "n",
        "row": "special",
        "example_word": "\u30d1\u30f3",
        "example_meaning": "bread",
    },
}

# =============================================================================
# DAKUTEN KATAKANA (voiced consonants)
# =============================================================================

KATAKANA_DAKUTEN = {
    "ga": {
        "character": "\u30ac",
        "romaji": "ga",
        "row": "g",
        "example_word": "\u30ac\u30e9\u30b9",
        "example_meaning": "glass",
    },
    "gi": {
        "character": "\u30ae",
        "romaji": "gi",
        "row": "g",
        "example_word": "\u30ae\u30bf\u30fc",
        "example_meaning": "guitar",
    },
    "gu": {
        "character": "\u30b0",
        "romaji": "gu",
        "row": "g",
        "example_word": "\u30b0\u30eb\u30fc\u30d7",
        "example_meaning": "group",
    },
    "ge": {
        "character": "\u30b2",
        "romaji": "ge",
        "row": "g",
        "example_word": "\u30b2\u30fc\u30e0",
        "example_meaning": "game",
    },
    "go": {
        "character": "\u30b4",
        "romaji": "go",
        "row": "g",
        "example_word": "\u30b4\u30eb\u30d5",
        "example_meaning": "golf",
    },
    "za": {
        "character": "\u30b6",
        "romaji": "za",
        "row": "z",
        "example_word": "\u30c7\u30b6\u30fc\u30c8",
        "example_meaning": "dessert",
    },
    "ji": {
        "character": "\u30b8",
        "romaji": "ji",
        "row": "z",
        "example_word": "\u30b8\u30e5\u30fc\u30b9",
        "example_meaning": "juice",
    },
    "zu": {
        "character": "\u30ba",
        "romaji": "zu",
        "row": "z",
        "example_word": "\u30c1\u30fc\u30ba",
        "example_meaning": "cheese",
    },
    "ze": {
        "character": "\u30bc",
        "romaji": "ze",
        "row": "z",
        "example_word": "\u30bc\u30ed",
        "example_meaning": "zero",
    },
    "zo": {
        "character": "\u30be",
        "romaji": "zo",
        "row": "z",
        "example_word": "\u30be\u30fc\u30f3",
        "example_meaning": "zone",
    },
    "da": {
        "character": "\u30c0",
        "romaji": "da",
        "row": "d",
        "example_word": "\u30c0\u30f3\u30b9",
        "example_meaning": "dance",
    },
    "di": {
        "character": "\u30c2",
        "romaji": "ji",
        "row": "d",
        "example_word": "\u30c2",
        "example_meaning": "(rarely used; ji/\u30b8 preferred)",
    },
    "du": {
        "character": "\u30c5",
        "romaji": "zu",
        "row": "d",
        "example_word": "\u30c5",
        "example_meaning": "(rarely used; zu/\u30ba preferred)",
    },
    "de": {
        "character": "\u30c7",
        "romaji": "de",
        "row": "d",
        "example_word": "\u30c7\u30d1\u30fc\u30c8",
        "example_meaning": "department store",
    },
    "do": {
        "character": "\u30c9",
        "romaji": "do",
        "row": "d",
        "example_word": "\u30c9\u30a2",
        "example_meaning": "door",
    },
    "ba": {
        "character": "\u30d0",
        "romaji": "ba",
        "row": "b",
        "example_word": "\u30d0\u30b9",
        "example_meaning": "bus",
    },
    "bi": {
        "character": "\u30d3",
        "romaji": "bi",
        "row": "b",
        "example_word": "\u30d3\u30fc\u30eb",
        "example_meaning": "beer",
    },
    "bu": {
        "character": "\u30d6",
        "romaji": "bu",
        "row": "b",
        "example_word": "\u30d6\u30e9\u30b8\u30eb",
        "example_meaning": "Brazil",
    },
    "be": {
        "character": "\u30d9",
        "romaji": "be",
        "row": "b",
        "example_word": "\u30d9\u30c3\u30c9",
        "example_meaning": "bed",
    },
    "bo": {
        "character": "\u30dc",
        "romaji": "bo",
        "row": "b",
        "example_word": "\u30dc\u30bf\u30f3",
        "example_meaning": "button",
    },
}

# =============================================================================
# HANDAKUTEN KATAKANA (p-sounds)
# =============================================================================

KATAKANA_HANDAKUTEN = {
    "pa": {
        "character": "\u30d1",
        "romaji": "pa",
        "row": "p",
        "example_word": "\u30d1\u30fc\u30c6\u30a3\u30fc",
        "example_meaning": "party",
    },
    "pi": {
        "character": "\u30d4",
        "romaji": "pi",
        "row": "p",
        "example_word": "\u30d4\u30a2\u30ce",
        "example_meaning": "piano",
    },
    "pu": {
        "character": "\u30d7",
        "romaji": "pu",
        "row": "p",
        "example_word": "\u30d7\u30ec\u30bc\u30f3\u30c8",
        "example_meaning": "present/gift",
    },
    "pe": {
        "character": "\u30da",
        "romaji": "pe",
        "row": "p",
        "example_word": "\u30da\u30f3",
        "example_meaning": "pen",
    },
    "po": {
        "character": "\u30dd",
        "romaji": "po",
        "row": "p",
        "example_word": "\u30dd\u30b1\u30c3\u30c8",
        "example_meaning": "pocket",
    },
}

# =============================================================================
# COMBINATION KATAKANA (youon)
# =============================================================================

KATAKANA_COMBOS = {
    "kya": {
        "character": "\u30ad\u30e3",
        "romaji": "kya",
        "row": "k-combo",
        "example_word": "\u30ad\u30e3\u30f3\u30d7",
        "example_meaning": "camp",
    },
    "kyu": {
        "character": "\u30ad\u30e5",
        "romaji": "kyu",
        "row": "k-combo",
        "example_word": "\u30d0\u30fc\u30d9\u30ad\u30e5\u30fc",
        "example_meaning": "barbecue",
    },
    "kyo": {
        "character": "\u30ad\u30e7",
        "romaji": "kyo",
        "row": "k-combo",
        "example_word": "\u30c8\u30fc\u30ad\u30e7\u30fc",
        "example_meaning": "Tokyo",
    },
    "sha": {
        "character": "\u30b7\u30e3",
        "romaji": "sha",
        "row": "s-combo",
        "example_word": "\u30b7\u30e3\u30ef\u30fc",
        "example_meaning": "shower",
    },
    "shu": {
        "character": "\u30b7\u30e5",
        "romaji": "shu",
        "row": "s-combo",
        "example_word": "\u30b7\u30e5\u30fc\u30ba",
        "example_meaning": "shoes",
    },
    "sho": {
        "character": "\u30b7\u30e7",
        "romaji": "sho",
        "row": "s-combo",
        "example_word": "\u30b7\u30e7\u30c3\u30d4\u30f3\u30b0",
        "example_meaning": "shopping",
    },
    "cha": {
        "character": "\u30c1\u30e3",
        "romaji": "cha",
        "row": "t-combo",
        "example_word": "\u30c1\u30e3\u30f3\u30cd\u30eb",
        "example_meaning": "channel",
    },
    "chu": {
        "character": "\u30c1\u30e5",
        "romaji": "chu",
        "row": "t-combo",
        "example_word": "\u30c1\u30e5\u30fc\u30ea\u30c3\u30d7",
        "example_meaning": "tulip",
    },
    "cho": {
        "character": "\u30c1\u30e7",
        "romaji": "cho",
        "row": "t-combo",
        "example_word": "\u30c1\u30e7\u30b3\u30ec\u30fc\u30c8",
        "example_meaning": "chocolate",
    },
    "nya": {
        "character": "\u30cb\u30e3",
        "romaji": "nya",
        "row": "n-combo",
        "example_word": "\u30cb\u30e3\u30f3",
        "example_meaning": "meow (cat sound)",
    },
    "nyu": {
        "character": "\u30cb\u30e5",
        "romaji": "nyu",
        "row": "n-combo",
        "example_word": "\u30cb\u30e5\u30fc\u30e8\u30fc\u30af",
        "example_meaning": "New York",
    },
    "nyo": {
        "character": "\u30cb\u30e7",
        "romaji": "nyo",
        "row": "n-combo",
        "example_word": "\u30cb\u30e7\u30c3\u30ad",
        "example_meaning": "gnocchi",
    },
    "hya": {
        "character": "\u30d2\u30e3",
        "romaji": "hya",
        "row": "h-combo",
        "example_word": "\u30d2\u30e3\u30c3\u30db\u30fc",
        "example_meaning": "(exclamation)",
    },
    "hyu": {
        "character": "\u30d2\u30e5",
        "romaji": "hyu",
        "row": "h-combo",
        "example_word": "\u30d2\u30e5\u30fc\u30ba",
        "example_meaning": "fuse",
    },
    "hyo": {
        "character": "\u30d2\u30e7",
        "romaji": "hyo",
        "row": "h-combo",
        "example_word": "\u30d2\u30e7\u30a6",
        "example_meaning": "leopard",
    },
    "mya": {
        "character": "\u30df\u30e3",
        "romaji": "mya",
        "row": "m-combo",
        "example_word": "\u30df\u30e3\u30f3\u30de\u30fc",
        "example_meaning": "Myanmar",
    },
    "myu": {
        "character": "\u30df\u30e5",
        "romaji": "myu",
        "row": "m-combo",
        "example_word": "\u30df\u30e5\u30fc\u30b8\u30c3\u30af",
        "example_meaning": "music",
    },
    "myo": {
        "character": "\u30df\u30e7",
        "romaji": "myo",
        "row": "m-combo",
        "example_word": "\u30df\u30e7\u30a6\u30ac",
        "example_meaning": "myoga (ginger)",
    },
    "rya": {
        "character": "\u30ea\u30e3",
        "romaji": "rya",
        "row": "r-combo",
        "example_word": "\u30ea\u30e3\u30c9",
        "example_meaning": "Riyadh",
    },
    "ryu": {
        "character": "\u30ea\u30e5",
        "romaji": "ryu",
        "row": "r-combo",
        "example_word": "\u30ea\u30e5\u30c3\u30af",
        "example_meaning": "backpack (rucksack)",
    },
    "ryo": {
        "character": "\u30ea\u30e7",
        "romaji": "ryo",
        "row": "r-combo",
        "example_word": "\u30ea\u30e7\u30ab\u30f3",
        "example_meaning": "travel agency",
    },
    "gya": {
        "character": "\u30ae\u30e3",
        "romaji": "gya",
        "row": "g-combo",
        "example_word": "\u30ae\u30e3\u30e9\u30ea\u30fc",
        "example_meaning": "gallery",
    },
    "gyu": {
        "character": "\u30ae\u30e5",
        "romaji": "gyu",
        "row": "g-combo",
        "example_word": "\u30ae\u30e5\u30c3\u30c8",
        "example_meaning": "packed/tight",
    },
    "gyo": {
        "character": "\u30ae\u30e7",
        "romaji": "gyo",
        "row": "g-combo",
        "example_word": "\u30ae\u30e7\u30fc\u30b6",
        "example_meaning": "gyoza (dumplings)",
    },
    "ja": {
        "character": "\u30b8\u30e3",
        "romaji": "ja",
        "row": "z-combo",
        "example_word": "\u30b8\u30e3\u30b1\u30c3\u30c8",
        "example_meaning": "jacket",
    },
    "ju": {
        "character": "\u30b8\u30e5",
        "romaji": "ju",
        "row": "z-combo",
        "example_word": "\u30b8\u30e5\u30fc\u30b9",
        "example_meaning": "juice",
    },
    "jo": {
        "character": "\u30b8\u30e7",
        "romaji": "jo",
        "row": "z-combo",
        "example_word": "\u30b8\u30e7\u30ae\u30f3\u30b0",
        "example_meaning": "jogging",
    },
    "bya": {
        "character": "\u30d3\u30e3",
        "romaji": "bya",
        "row": "b-combo",
        "example_word": "\u30d3\u30e3\u30af\u30e4",
        "example_meaning": "hundred-yen shop (Byakuya)",
    },
    "byu": {
        "character": "\u30d3\u30e5",
        "romaji": "byu",
        "row": "b-combo",
        "example_word": "\u30d3\u30e5\u30fc\u30c6\u30a3\u30fc",
        "example_meaning": "beauty",
    },
    "byo": {
        "character": "\u30d3\u30e7",
        "romaji": "byo",
        "row": "b-combo",
        "example_word": "\u30d3\u30e7\u30a6\u30a4\u30f3",
        "example_meaning": "hospital (byouin)",
    },
    "pya": {
        "character": "\u30d4\u30e3",
        "romaji": "pya",
        "row": "p-combo",
        "example_word": "\u30d4\u30e3\u30ce",
        "example_meaning": "(variant of piano)",
    },
    "pyu": {
        "character": "\u30d4\u30e5",
        "romaji": "pyu",
        "row": "p-combo",
        "example_word": "\u30b3\u30f3\u30d4\u30e5\u30fc\u30bf\u30fc",
        "example_meaning": "computer",
    },
    "pyo": {
        "character": "\u30d4\u30e7",
        "romaji": "pyo",
        "row": "p-combo",
        "example_word": "\u30d4\u30e7\u30f3\u30e4\u30f3",
        "example_meaning": "Pyongyang",
    },
}

# =============================================================================
# KATAKANA LESSONS
# =============================================================================

KATAKANA_LESSONS = [
    {
        "lesson_id": "kata_01",
        "title": "Katakana Vowels",
        "description": "Learn the five katakana vowels, used for foreign loanwords.",
        "characters_taught": ["a", "i", "u", "e", "o"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_02",
        "title": "K-Row Katakana",
        "description": "Master the katakana k-row for words like camera and coffee.",
        "characters_taught": ["ka", "ki", "ku", "ke", "ko"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_03",
        "title": "S-Row Katakana",
        "description": "Learn s-row katakana for words like sports and salad.",
        "characters_taught": ["sa", "shi", "su", "se", "so"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_04",
        "title": "T-Row Katakana",
        "description": "Master t-row katakana for taxi, test, and more.",
        "characters_taught": ["ta", "chi", "tsu", "te", "to"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_05",
        "title": "N-Row Katakana",
        "description": "Learn n-row katakana for news, knife, and notebook.",
        "characters_taught": ["na", "ni", "nu", "ne", "no"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_06",
        "title": "H-Row Katakana",
        "description": "Master h-row katakana for hotel, hamburger, and France.",
        "characters_taught": ["ha", "hi", "fu", "he", "ho"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_07",
        "title": "M-Row Katakana",
        "description": "Learn m-row katakana for milk, menu, and movie.",
        "characters_taught": ["ma", "mi", "mu", "me", "mo"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_08",
        "title": "Y-Row, W-Row, and N Katakana",
        "description": "Complete basic katakana with the remaining characters.",
        "characters_taught": ["ya", "yu", "yo", "wa", "wo", "n"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_09",
        "title": "R-Row Katakana",
        "description": "Master r-row katakana for radio, restaurant, and robot.",
        "characters_taught": ["ra", "ri", "ru", "re", "ro"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_10",
        "title": "Katakana Dakuten",
        "description": "Learn voiced katakana for game, dance, bus, and more.",
        "characters_taught": [
            "ga", "gi", "gu", "ge", "go",
            "za", "ji", "zu", "ze", "zo",
            "da", "di", "du", "de", "do",
            "ba", "bi", "bu", "be", "bo",
        ],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_11",
        "title": "Katakana Handakuten",
        "description": "Learn p-sound katakana for party, piano, and pen.",
        "characters_taught": ["pa", "pi", "pu", "pe", "po"],
        "monument_id": 1,
    },
    {
        "lesson_id": "kata_12",
        "title": "Katakana Combinations",
        "description": "Master combination katakana for chocolate, shopping, and juice.",
        "characters_taught": [
            "kya", "kyu", "kyo", "sha", "shu", "sho",
            "cha", "chu", "cho", "nya", "nyu", "nyo",
            "hya", "hyu", "hyo", "mya", "myu", "myo",
            "rya", "ryu", "ryo", "gya", "gyu", "gyo",
            "ja", "ju", "jo", "bya", "byu", "byo",
            "pya", "pyu", "pyo",
        ],
        "monument_id": 1,
    },
]
