"""
Nihongo Quest - Vocabulary Content Data
Essential Japanese vocabulary organized by category.
Monument ID: 3 (The Vocabulary Garden)
"""

# =============================================================================
# GREETINGS (20+ common greetings)
# =============================================================================

GREETINGS = [
    {
        "japanese": "おはようございます",
        "romaji": "ohayou gozaimasu",
        "english": "Good morning (polite)",
        "example_sentence": "おはようございます、せんせい。",
    },
    {
        "japanese": "おはよう",
        "romaji": "ohayou",
        "english": "Good morning (casual)",
        "example_sentence": "おはよう、ともだち！",
    },
    {
        "japanese": "こんにちは",
        "romaji": "konnichiwa",
        "english": "Good afternoon / Hello",
        "example_sentence": "こんにちは、おげんきですか。",
    },
    {
        "japanese": "こんばんは",
        "romaji": "konbanwa",
        "english": "Good evening",
        "example_sentence": "こんばんは、きょうはさむいですね。",
    },
    {
        "japanese": "おやすみなさい",
        "romaji": "oyasuminasai",
        "english": "Good night",
        "example_sentence": "おやすみなさい、あしたまた。",
    },
    {
        "japanese": "さようなら",
        "romaji": "sayounara",
        "english": "Goodbye",
        "example_sentence": "さようなら、またあいましょう。",
    },
    {
        "japanese": "じゃあね",
        "romaji": "jaa ne",
        "english": "See you (casual)",
        "example_sentence": "じゃあね、きをつけて！",
    },
    {
        "japanese": "ありがとうございます",
        "romaji": "arigatou gozaimasu",
        "english": "Thank you (polite)",
        "example_sentence": "たすけてくれて、ありがとうございます。",
    },
    {
        "japanese": "ありがとう",
        "romaji": "arigatou",
        "english": "Thank you (casual)",
        "example_sentence": "ありがとう、たすかったよ。",
    },
    {
        "japanese": "すみません",
        "romaji": "sumimasen",
        "english": "Excuse me / I'm sorry",
        "example_sentence": "すみません、えきはどこですか。",
    },
    {
        "japanese": "ごめんなさい",
        "romaji": "gomen nasai",
        "english": "I'm sorry (apology)",
        "example_sentence": "おそくなって、ごめんなさい。",
    },
    {
        "japanese": "はじめまして",
        "romaji": "hajimemashite",
        "english": "Nice to meet you (first time)",
        "example_sentence": "はじめまして、たなかです。",
    },
    {
        "japanese": "よろしくおねがいします",
        "romaji": "yoroshiku onegai shimasu",
        "english": "Please treat me well / Nice to meet you",
        "example_sentence": "たなかです。よろしくおねがいします。",
    },
    {
        "japanese": "おげんきですか",
        "romaji": "ogenki desu ka",
        "english": "How are you?",
        "example_sentence": "おげんきですか。はい、げんきです。",
    },
    {
        "japanese": "いただきます",
        "romaji": "itadakimasu",
        "english": "Let's eat (before meals)",
        "example_sentence": "いただきます！おいしそうですね。",
    },
    {
        "japanese": "ごちそうさまでした",
        "romaji": "gochisousama deshita",
        "english": "Thank you for the meal (after eating)",
        "example_sentence": "ごちそうさまでした、おいしかったです。",
    },
    {
        "japanese": "いってきます",
        "romaji": "ittekimasu",
        "english": "I'm leaving (said when going out)",
        "example_sentence": "いってきます！がっこうにいきます。",
    },
    {
        "japanese": "いってらっしゃい",
        "romaji": "itterasshai",
        "english": "Have a good trip (response to ittekimasu)",
        "example_sentence": "いってらっしゃい、きをつけてね。",
    },
    {
        "japanese": "ただいま",
        "romaji": "tadaima",
        "english": "I'm home",
        "example_sentence": "ただいま！つかれた。",
    },
    {
        "japanese": "おかえりなさい",
        "romaji": "okaerinasai",
        "english": "Welcome home",
        "example_sentence": "おかえりなさい、ごはんできてるよ。",
    },
    {
        "japanese": "おめでとうございます",
        "romaji": "omedetou gozaimasu",
        "english": "Congratulations (polite)",
        "example_sentence": "たんじょうびおめでとうございます！",
    },
    {
        "japanese": "おつかれさまでした",
        "romaji": "otsukaresama deshita",
        "english": "Good work / Thank you for your hard work",
        "example_sentence": "おつかれさまでした、おさきにしつれいします。",
    },
]

# =============================================================================
# NUMBERS (0-100 + counters)
# =============================================================================

NUMBERS = {
    "basic": [
        {"number": 0, "japanese": "ゼロ/れい", "romaji": "zero/rei"},
        {"number": 1, "japanese": "いち", "romaji": "ichi"},
        {"number": 2, "japanese": "に", "romaji": "ni"},
        {"number": 3, "japanese": "さん", "romaji": "san"},
        {"number": 4, "japanese": "し/よん", "romaji": "shi/yon"},
        {"number": 5, "japanese": "ご", "romaji": "go"},
        {"number": 6, "japanese": "ろく", "romaji": "roku"},
        {"number": 7, "japanese": "しち/なな", "romaji": "shichi/nana"},
        {"number": 8, "japanese": "はち", "romaji": "hachi"},
        {"number": 9, "japanese": "きゅう/く", "romaji": "kyuu/ku"},
        {"number": 10, "japanese": "じゅう", "romaji": "juu"},
        {"number": 11, "japanese": "じゅういち", "romaji": "juuichi"},
        {"number": 12, "japanese": "じゅうに", "romaji": "juuni"},
        {"number": 13, "japanese": "じゅうさん", "romaji": "juusan"},
        {"number": 14, "japanese": "じゅうよん", "romaji": "juuyon"},
        {"number": 15, "japanese": "じゅうご", "romaji": "juugo"},
        {"number": 16, "japanese": "じゅうろく", "romaji": "juuroku"},
        {"number": 17, "japanese": "じゅうなな", "romaji": "juunana"},
        {"number": 18, "japanese": "じゅうはち", "romaji": "juuhachi"},
        {"number": 19, "japanese": "じゅうきゅう", "romaji": "juukyuu"},
        {"number": 20, "japanese": "にじゅう", "romaji": "nijuu"},
        {"number": 30, "japanese": "さんじゅう", "romaji": "sanjuu"},
        {"number": 40, "japanese": "よんじゅう", "romaji": "yonjuu"},
        {"number": 50, "japanese": "ごじゅう", "romaji": "gojuu"},
        {"number": 60, "japanese": "ろくじゅう", "romaji": "rokujuu"},
        {"number": 70, "japanese": "ななじゅう", "romaji": "nanajuu"},
        {"number": 80, "japanese": "はちじゅう", "romaji": "hachijuu"},
        {"number": 90, "japanese": "きゅうじゅう", "romaji": "kyuujuu"},
        {"number": 100, "japanese": "ひゃく", "romaji": "hyaku"},
    ],
    "counters": [
        {
            "counter": "つ",
            "romaji": "tsu",
            "usage": "General counter for things",
            "examples": [
                {"count": "ひとつ", "romaji": "hitotsu", "meaning": "one thing"},
                {"count": "ふたつ", "romaji": "futatsu", "meaning": "two things"},
                {"count": "みっつ", "romaji": "mittsu", "meaning": "three things"},
                {"count": "よっつ", "romaji": "yottsu", "meaning": "four things"},
                {"count": "いつつ", "romaji": "itsutsu", "meaning": "five things"},
                {"count": "むっつ", "romaji": "muttsu", "meaning": "six things"},
                {"count": "ななつ", "romaji": "nanatsu", "meaning": "seven things"},
                {"count": "やっつ", "romaji": "yattsu", "meaning": "eight things"},
                {"count": "ここのつ", "romaji": "kokonotsu", "meaning": "nine things"},
                {"count": "とお", "romaji": "too", "meaning": "ten things"},
            ],
        },
        {
            "counter": "人",
            "romaji": "nin/ri",
            "usage": "Counter for people",
            "examples": [
                {"count": "ひとり", "romaji": "hitori", "meaning": "one person"},
                {"count": "ふたり", "romaji": "futari", "meaning": "two people"},
                {"count": "さんにん", "romaji": "sannin", "meaning": "three people"},
                {"count": "よにん", "romaji": "yonin", "meaning": "four people"},
                {"count": "ごにん", "romaji": "gonin", "meaning": "five people"},
            ],
        },
        {
            "counter": "匹",
            "romaji": "hiki/biki/piki",
            "usage": "Counter for small animals",
            "examples": [
                {"count": "いっぴき", "romaji": "ippiki", "meaning": "one animal"},
                {"count": "にひき", "romaji": "nihiki", "meaning": "two animals"},
                {"count": "さんびき", "romaji": "sanbiki", "meaning": "three animals"},
            ],
        },
        {
            "counter": "本",
            "romaji": "hon/bon/pon",
            "usage": "Counter for long, thin objects (pens, bottles, etc.)",
            "examples": [
                {"count": "いっぽん", "romaji": "ippon", "meaning": "one (long thing)"},
                {"count": "にほん", "romaji": "nihon", "meaning": "two (long things)"},
                {"count": "さんぼん", "romaji": "sanbon", "meaning": "three (long things)"},
            ],
        },
        {
            "counter": "枚",
            "romaji": "mai",
            "usage": "Counter for flat objects (paper, tickets, etc.)",
            "examples": [
                {"count": "いちまい", "romaji": "ichimai", "meaning": "one (flat thing)"},
                {"count": "にまい", "romaji": "nimai", "meaning": "two (flat things)"},
                {"count": "さんまい", "romaji": "sanmai", "meaning": "three (flat things)"},
            ],
        },
        {
            "counter": "台",
            "romaji": "dai",
            "usage": "Counter for machines and vehicles",
            "examples": [
                {"count": "いちだい", "romaji": "ichidai", "meaning": "one machine/vehicle"},
                {"count": "にだい", "romaji": "nidai", "meaning": "two machines/vehicles"},
            ],
        },
        {
            "counter": "杯",
            "romaji": "hai/bai/pai",
            "usage": "Counter for cups and glasses of liquid",
            "examples": [
                {"count": "いっぱい", "romaji": "ippai", "meaning": "one cup/glass"},
                {"count": "にはい", "romaji": "nihai", "meaning": "two cups/glasses"},
                {"count": "さんばい", "romaji": "sanbai", "meaning": "three cups/glasses"},
            ],
        },
        {
            "counter": "冊",
            "romaji": "satsu",
            "usage": "Counter for books and bound volumes",
            "examples": [
                {"count": "いっさつ", "romaji": "issatsu", "meaning": "one book"},
                {"count": "にさつ", "romaji": "nisatsu", "meaning": "two books"},
            ],
        },
    ],
}

# =============================================================================
# COMMON NOUNS (50+ organized by topic)
# =============================================================================

COMMON_NOUNS = {
    "family": [
        {"japanese": "かぞく", "romaji": "kazoku", "english": "family"},
        {"japanese": "おかあさん", "romaji": "okaasan", "english": "mother (someone else's)"},
        {"japanese": "はは", "romaji": "haha", "english": "mother (one's own)"},
        {"japanese": "おとうさん", "romaji": "otousan", "english": "father (someone else's)"},
        {"japanese": "ちち", "romaji": "chichi", "english": "father (one's own)"},
        {"japanese": "おにいさん", "romaji": "oniisan", "english": "older brother (someone else's)"},
        {"japanese": "あに", "romaji": "ani", "english": "older brother (one's own)"},
        {"japanese": "おねえさん", "romaji": "oneesan", "english": "older sister (someone else's)"},
        {"japanese": "あね", "romaji": "ane", "english": "older sister (one's own)"},
        {"japanese": "おとうと", "romaji": "otouto", "english": "younger brother"},
        {"japanese": "いもうと", "romaji": "imouto", "english": "younger sister"},
    ],
    "food": [
        {"japanese": "ごはん", "romaji": "gohan", "english": "rice / meal"},
        {"japanese": "パン", "romaji": "pan", "english": "bread"},
        {"japanese": "にく", "romaji": "niku", "english": "meat"},
        {"japanese": "さかな", "romaji": "sakana", "english": "fish"},
        {"japanese": "やさい", "romaji": "yasai", "english": "vegetables"},
        {"japanese": "くだもの", "romaji": "kudamono", "english": "fruit"},
        {"japanese": "たまご", "romaji": "tamago", "english": "egg"},
        {"japanese": "みず", "romaji": "mizu", "english": "water"},
        {"japanese": "おちゃ", "romaji": "ocha", "english": "tea"},
        {"japanese": "ぎゅうにゅう", "romaji": "gyuunyuu", "english": "milk"},
    ],
    "animals": [
        {"japanese": "いぬ", "romaji": "inu", "english": "dog"},
        {"japanese": "ねこ", "romaji": "neko", "english": "cat"},
        {"japanese": "とり", "romaji": "tori", "english": "bird"},
        {"japanese": "さかな", "romaji": "sakana", "english": "fish"},
        {"japanese": "うま", "romaji": "uma", "english": "horse"},
        {"japanese": "うし", "romaji": "ushi", "english": "cow"},
        {"japanese": "ぶた", "romaji": "buta", "english": "pig"},
    ],
    "body": [
        {"japanese": "あたま", "romaji": "atama", "english": "head"},
        {"japanese": "かお", "romaji": "kao", "english": "face"},
        {"japanese": "め", "romaji": "me", "english": "eye"},
        {"japanese": "みみ", "romaji": "mimi", "english": "ear"},
        {"japanese": "くち", "romaji": "kuchi", "english": "mouth"},
        {"japanese": "はな", "romaji": "hana", "english": "nose"},
        {"japanese": "て", "romaji": "te", "english": "hand"},
        {"japanese": "あし", "romaji": "ashi", "english": "leg / foot"},
    ],
    "house": [
        {"japanese": "いえ/うち", "romaji": "ie/uchi", "english": "house / home"},
        {"japanese": "へや", "romaji": "heya", "english": "room"},
        {"japanese": "だいどころ", "romaji": "daidokoro", "english": "kitchen"},
        {"japanese": "おふろ", "romaji": "ofuro", "english": "bath"},
        {"japanese": "トイレ", "romaji": "toire", "english": "toilet"},
        {"japanese": "まど", "romaji": "mado", "english": "window"},
        {"japanese": "ドア", "romaji": "doa", "english": "door"},
    ],
    "nature": [
        {"japanese": "そら", "romaji": "sora", "english": "sky"},
        {"japanese": "やま", "romaji": "yama", "english": "mountain"},
        {"japanese": "かわ", "romaji": "kawa", "english": "river"},
        {"japanese": "うみ", "romaji": "umi", "english": "sea"},
        {"japanese": "き", "romaji": "ki", "english": "tree"},
        {"japanese": "はな", "romaji": "hana", "english": "flower"},
        {"japanese": "あめ", "romaji": "ame", "english": "rain"},
    ],
    "school": [
        {"japanese": "がっこう", "romaji": "gakkou", "english": "school"},
        {"japanese": "せんせい", "romaji": "sensei", "english": "teacher"},
        {"japanese": "がくせい", "romaji": "gakusei", "english": "student"},
        {"japanese": "きょうしつ", "romaji": "kyoushitsu", "english": "classroom"},
        {"japanese": "ほん", "romaji": "hon", "english": "book"},
        {"japanese": "えんぴつ", "romaji": "enpitsu", "english": "pencil"},
        {"japanese": "ノート", "romaji": "nooto", "english": "notebook"},
    ],
    "time": [
        {"japanese": "いま", "romaji": "ima", "english": "now"},
        {"japanese": "きょう", "romaji": "kyou", "english": "today"},
        {"japanese": "あした", "romaji": "ashita", "english": "tomorrow"},
        {"japanese": "きのう", "romaji": "kinou", "english": "yesterday"},
        {"japanese": "あさ", "romaji": "asa", "english": "morning"},
        {"japanese": "ひる", "romaji": "hiru", "english": "noon / daytime"},
        {"japanese": "よる", "romaji": "yoru", "english": "night"},
        {"japanese": "まいにち", "romaji": "mainichi", "english": "every day"},
    ],
}

# =============================================================================
# COMMON VERBS (40+ essential verbs)
# =============================================================================

COMMON_VERBS = [
    {
        "dictionary_form": "たべる",
        "masu_form": "たべます",
        "te_form": "たべて",
        "past_form": "たべた",
        "meaning": "to eat",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "のむ",
        "masu_form": "のみます",
        "te_form": "のんで",
        "past_form": "のんだ",
        "meaning": "to drink",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "みる",
        "masu_form": "みます",
        "te_form": "みて",
        "past_form": "みた",
        "meaning": "to see / to watch",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "きく",
        "masu_form": "ききます",
        "te_form": "きいて",
        "past_form": "きいた",
        "meaning": "to listen / to ask",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "はなす",
        "masu_form": "はなします",
        "te_form": "はなして",
        "past_form": "はなした",
        "meaning": "to speak",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "よむ",
        "masu_form": "よみます",
        "te_form": "よんで",
        "past_form": "よんだ",
        "meaning": "to read",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "かく",
        "masu_form": "かきます",
        "te_form": "かいて",
        "past_form": "かいた",
        "meaning": "to write",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "いく",
        "masu_form": "いきます",
        "te_form": "いって",
        "past_form": "いった",
        "meaning": "to go",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "くる",
        "masu_form": "きます",
        "te_form": "きて",
        "past_form": "きた",
        "meaning": "to come",
        "verb_type": "irregular",
    },
    {
        "dictionary_form": "する",
        "masu_form": "します",
        "te_form": "して",
        "past_form": "した",
        "meaning": "to do",
        "verb_type": "irregular",
    },
    {
        "dictionary_form": "ある",
        "masu_form": "あります",
        "te_form": "あって",
        "past_form": "あった",
        "meaning": "to exist (inanimate)",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "いる",
        "masu_form": "います",
        "te_form": "いて",
        "past_form": "いた",
        "meaning": "to exist (animate)",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "かう",
        "masu_form": "かいます",
        "te_form": "かって",
        "past_form": "かった",
        "meaning": "to buy",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "まつ",
        "masu_form": "まちます",
        "te_form": "まって",
        "past_form": "まった",
        "meaning": "to wait",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "のる",
        "masu_form": "のります",
        "te_form": "のって",
        "past_form": "のった",
        "meaning": "to ride / to get on",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "おりる",
        "masu_form": "おります",
        "te_form": "おりて",
        "past_form": "おりた",
        "meaning": "to get off / to descend",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "あるく",
        "masu_form": "あるきます",
        "te_form": "あるいて",
        "past_form": "あるいた",
        "meaning": "to walk",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "はしる",
        "masu_form": "はしります",
        "te_form": "はしって",
        "past_form": "はしった",
        "meaning": "to run",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "およぐ",
        "masu_form": "およぎます",
        "te_form": "およいで",
        "past_form": "およいだ",
        "meaning": "to swim",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "あそぶ",
        "masu_form": "あそびます",
        "te_form": "あそんで",
        "past_form": "あそんだ",
        "meaning": "to play",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "ねる",
        "masu_form": "ねます",
        "te_form": "ねて",
        "past_form": "ねた",
        "meaning": "to sleep",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "おきる",
        "masu_form": "おきます",
        "te_form": "おきて",
        "past_form": "おきた",
        "meaning": "to wake up",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "つくる",
        "masu_form": "つくります",
        "te_form": "つくって",
        "past_form": "つくった",
        "meaning": "to make",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "つかう",
        "masu_form": "つかいます",
        "te_form": "つかって",
        "past_form": "つかった",
        "meaning": "to use",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "わかる",
        "masu_form": "わかります",
        "te_form": "わかって",
        "past_form": "わかった",
        "meaning": "to understand",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "おしえる",
        "masu_form": "おしえます",
        "te_form": "おしえて",
        "past_form": "おしえた",
        "meaning": "to teach / to tell",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "ならう",
        "masu_form": "ならいます",
        "te_form": "ならって",
        "past_form": "ならった",
        "meaning": "to learn",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "べんきょうする",
        "masu_form": "べんきょうします",
        "te_form": "べんきょうして",
        "past_form": "べんきょうした",
        "meaning": "to study",
        "verb_type": "irregular",
    },
    {
        "dictionary_form": "しごとする",
        "masu_form": "しごとします",
        "te_form": "しごとして",
        "past_form": "しごとした",
        "meaning": "to work",
        "verb_type": "irregular",
    },
    {
        "dictionary_form": "あう",
        "masu_form": "あいます",
        "te_form": "あって",
        "past_form": "あった",
        "meaning": "to meet",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "もつ",
        "masu_form": "もちます",
        "te_form": "もって",
        "past_form": "もった",
        "meaning": "to hold / to have",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "しぬ",
        "masu_form": "しにます",
        "te_form": "しんで",
        "past_form": "しんだ",
        "meaning": "to die",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "あげる",
        "masu_form": "あげます",
        "te_form": "あげて",
        "past_form": "あげた",
        "meaning": "to give (to someone)",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "もらう",
        "masu_form": "もらいます",
        "te_form": "もらって",
        "past_form": "もらった",
        "meaning": "to receive",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "くれる",
        "masu_form": "くれます",
        "te_form": "くれて",
        "past_form": "くれた",
        "meaning": "to give (to me/us)",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "かえる",
        "masu_form": "かえります",
        "te_form": "かえって",
        "past_form": "かえった",
        "meaning": "to return (home)",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "おもう",
        "masu_form": "おもいます",
        "te_form": "おもって",
        "past_form": "おもった",
        "meaning": "to think",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "しる",
        "masu_form": "しります",
        "te_form": "しって",
        "past_form": "しった",
        "meaning": "to know",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "すむ",
        "masu_form": "すみます",
        "te_form": "すんで",
        "past_form": "すんだ",
        "meaning": "to live (reside)",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "きる",
        "masu_form": "きます",
        "te_form": "きて",
        "past_form": "きた",
        "meaning": "to wear (upper body)",
        "verb_type": "ichidan",
    },
    {
        "dictionary_form": "とる",
        "masu_form": "とります",
        "te_form": "とって",
        "past_form": "とった",
        "meaning": "to take",
        "verb_type": "godan",
    },
    {
        "dictionary_form": "おくる",
        "masu_form": "おくります",
        "te_form": "おくって",
        "past_form": "おくった",
        "meaning": "to send",
        "verb_type": "godan",
    },
]

# =============================================================================
# COMMON ADJECTIVES (30+, split into i-adjectives and na-adjectives)
# =============================================================================

COMMON_ADJECTIVES = {
    "i_adjectives": [
        {
            "japanese": "おおきい",
            "romaji": "ookii",
            "english": "big",
            "negative": "おおきくない",
            "past": "おおきかった",
            "past_negative": "おおきくなかった",
        },
        {
            "japanese": "ちいさい",
            "romaji": "chiisai",
            "english": "small",
            "negative": "ちいさくない",
            "past": "ちいさかった",
            "past_negative": "ちいさくなかった",
        },
        {
            "japanese": "たかい",
            "romaji": "takai",
            "english": "expensive / tall",
            "negative": "たかくない",
            "past": "たかかった",
            "past_negative": "たかくなかった",
        },
        {
            "japanese": "やすい",
            "romaji": "yasui",
            "english": "cheap",
            "negative": "やすくない",
            "past": "やすかった",
            "past_negative": "やすくなかった",
        },
        {
            "japanese": "あたらしい",
            "romaji": "atarashii",
            "english": "new",
            "negative": "あたらしくない",
            "past": "あたらしかった",
            "past_negative": "あたらしくなかった",
        },
        {
            "japanese": "ふるい",
            "romaji": "furui",
            "english": "old (things)",
            "negative": "ふるくない",
            "past": "ふるかった",
            "past_negative": "ふるくなかった",
        },
        {
            "japanese": "いい/よい",
            "romaji": "ii/yoi",
            "english": "good",
            "negative": "よくない",
            "past": "よかった",
            "past_negative": "よくなかった",
        },
        {
            "japanese": "わるい",
            "romaji": "warui",
            "english": "bad",
            "negative": "わるくない",
            "past": "わるかった",
            "past_negative": "わるくなかった",
        },
        {
            "japanese": "あつい",
            "romaji": "atsui",
            "english": "hot (weather/things)",
            "negative": "あつくない",
            "past": "あつかった",
            "past_negative": "あつくなかった",
        },
        {
            "japanese": "さむい",
            "romaji": "samui",
            "english": "cold (weather)",
            "negative": "さむくない",
            "past": "さむかった",
            "past_negative": "さむくなかった",
        },
        {
            "japanese": "つめたい",
            "romaji": "tsumetai",
            "english": "cold (to touch/drinks)",
            "negative": "つめたくない",
            "past": "つめたかった",
            "past_negative": "つめたくなかった",
        },
        {
            "japanese": "おいしい",
            "romaji": "oishii",
            "english": "delicious",
            "negative": "おいしくない",
            "past": "おいしかった",
            "past_negative": "おいしくなかった",
        },
        {
            "japanese": "まずい",
            "romaji": "mazui",
            "english": "bad tasting",
            "negative": "まずくない",
            "past": "まずかった",
            "past_negative": "まずくなかった",
        },
        {
            "japanese": "はやい",
            "romaji": "hayai",
            "english": "fast / early",
            "negative": "はやくない",
            "past": "はやかった",
            "past_negative": "はやくなかった",
        },
        {
            "japanese": "おそい",
            "romaji": "osoi",
            "english": "slow / late",
            "negative": "おそくない",
            "past": "おそかった",
            "past_negative": "おそくなかった",
        },
        {
            "japanese": "ながい",
            "romaji": "nagai",
            "english": "long",
            "negative": "ながくない",
            "past": "ながかった",
            "past_negative": "ながくなかった",
        },
        {
            "japanese": "みじかい",
            "romaji": "mijikai",
            "english": "short (length)",
            "negative": "みじかくない",
            "past": "みじかかった",
            "past_negative": "みじかくなかった",
        },
        {
            "japanese": "たのしい",
            "romaji": "tanoshii",
            "english": "fun / enjoyable",
            "negative": "たのしくない",
            "past": "たのしかった",
            "past_negative": "たのしくなかった",
        },
        {
            "japanese": "むずかしい",
            "romaji": "muzukashii",
            "english": "difficult",
            "negative": "むずかしくない",
            "past": "むずかしかった",
            "past_negative": "むずかしくなかった",
        },
        {
            "japanese": "やさしい",
            "romaji": "yasashii",
            "english": "easy / kind",
            "negative": "やさしくない",
            "past": "やさしかった",
            "past_negative": "やさしくなかった",
        },
    ],
    "na_adjectives": [
        {
            "japanese": "げんき",
            "romaji": "genki",
            "english": "healthy / energetic",
            "na_form": "げんきな",
            "negative": "げんきじゃない",
            "past": "げんきだった",
            "past_negative": "げんきじゃなかった",
        },
        {
            "japanese": "しずか",
            "romaji": "shizuka",
            "english": "quiet",
            "na_form": "しずかな",
            "negative": "しずかじゃない",
            "past": "しずかだった",
            "past_negative": "しずかじゃなかった",
        },
        {
            "japanese": "にぎやか",
            "romaji": "nigiyaka",
            "english": "lively",
            "na_form": "にぎやかな",
            "negative": "にぎやかじゃない",
            "past": "にぎやかだった",
            "past_negative": "にぎやかじゃなかった",
        },
        {
            "japanese": "きれい",
            "romaji": "kirei",
            "english": "beautiful / clean",
            "na_form": "きれいな",
            "negative": "きれいじゃない",
            "past": "きれいだった",
            "past_negative": "きれいじゃなかった",
        },
        {
            "japanese": "ゆうめい",
            "romaji": "yuumei",
            "english": "famous",
            "na_form": "ゆうめいな",
            "negative": "ゆうめいじゃない",
            "past": "ゆうめいだった",
            "past_negative": "ゆうめいじゃなかった",
        },
        {
            "japanese": "しんせつ",
            "romaji": "shinsetsu",
            "english": "kind",
            "na_form": "しんせつな",
            "negative": "しんせつじゃない",
            "past": "しんせつだった",
            "past_negative": "しんせつじゃなかった",
        },
        {
            "japanese": "べんり",
            "romaji": "benri",
            "english": "convenient",
            "na_form": "べんりな",
            "negative": "べんりじゃない",
            "past": "べんりだった",
            "past_negative": "べんりじゃなかった",
        },
        {
            "japanese": "ひま",
            "romaji": "hima",
            "english": "free (not busy)",
            "na_form": "ひまな",
            "negative": "ひまじゃない",
            "past": "ひまだった",
            "past_negative": "ひまじゃなかった",
        },
        {
            "japanese": "たいへん",
            "romaji": "taihen",
            "english": "tough / serious",
            "na_form": "たいへんな",
            "negative": "たいへんじゃない",
            "past": "たいへんだった",
            "past_negative": "たいへんじゃなかった",
        },
        {
            "japanese": "すき",
            "romaji": "suki",
            "english": "liked / favorite",
            "na_form": "すきな",
            "negative": "すきじゃない",
            "past": "すきだった",
            "past_negative": "すきじゃなかった",
        },
        {
            "japanese": "きらい",
            "romaji": "kirai",
            "english": "disliked",
            "na_form": "きらいな",
            "negative": "きらいじゃない",
            "past": "きらいだった",
            "past_negative": "きらいじゃなかった",
        },
        {
            "japanese": "じょうず",
            "romaji": "jouzu",
            "english": "skillful",
            "na_form": "じょうずな",
            "negative": "じょうずじゃない",
            "past": "じょうずだった",
            "past_negative": "じょうずじゃなかった",
        },
        {
            "japanese": "へた",
            "romaji": "heta",
            "english": "unskillful",
            "na_form": "へたな",
            "negative": "へたじゃない",
            "past": "へただった",
            "past_negative": "へたじゃなかった",
        },
        {
            "japanese": "だいじ",
            "romaji": "daiji",
            "english": "important",
            "na_form": "だいじな",
            "negative": "だいじじゃない",
            "past": "だいじだった",
            "past_negative": "だいじじゃなかった",
        },
    ],
}

# =============================================================================
# JLPT N5 VOCABULARY (~100 most important words)
# =============================================================================

JLPT_N5_VOCAB = [
    {"japanese": "わたし", "romaji": "watashi", "english": "I / me", "pos": "pronoun"},
    {"japanese": "あなた", "romaji": "anata", "english": "you", "pos": "pronoun"},
    {"japanese": "かれ", "romaji": "kare", "english": "he / him", "pos": "pronoun"},
    {"japanese": "かのじょ", "romaji": "kanojo", "english": "she / her", "pos": "pronoun"},
    {"japanese": "これ", "romaji": "kore", "english": "this (thing)", "pos": "pronoun"},
    {"japanese": "それ", "romaji": "sore", "english": "that (thing near listener)", "pos": "pronoun"},
    {"japanese": "あれ", "romaji": "are", "english": "that (thing over there)", "pos": "pronoun"},
    {"japanese": "ここ", "romaji": "koko", "english": "here", "pos": "pronoun"},
    {"japanese": "そこ", "romaji": "soko", "english": "there", "pos": "pronoun"},
    {"japanese": "あそこ", "romaji": "asoko", "english": "over there", "pos": "pronoun"},
    {"japanese": "だれ", "romaji": "dare", "english": "who", "pos": "pronoun"},
    {"japanese": "なに/なん", "romaji": "nani/nan", "english": "what", "pos": "pronoun"},
    {"japanese": "どこ", "romaji": "doko", "english": "where", "pos": "pronoun"},
    {"japanese": "いつ", "romaji": "itsu", "english": "when", "pos": "pronoun"},
    {"japanese": "どう", "romaji": "dou", "english": "how", "pos": "adverb"},
    {"japanese": "なぜ/どうして", "romaji": "naze/doushite", "english": "why", "pos": "adverb"},
    {"japanese": "ひと", "romaji": "hito", "english": "person", "pos": "noun"},
    {"japanese": "おとこ", "romaji": "otoko", "english": "man / male", "pos": "noun"},
    {"japanese": "おんな", "romaji": "onna", "english": "woman / female", "pos": "noun"},
    {"japanese": "こども", "romaji": "kodomo", "english": "child", "pos": "noun"},
    {"japanese": "ともだち", "romaji": "tomodachi", "english": "friend", "pos": "noun"},
    {"japanese": "にほんご", "romaji": "nihongo", "english": "Japanese language", "pos": "noun"},
    {"japanese": "えいご", "romaji": "eigo", "english": "English language", "pos": "noun"},
    {"japanese": "でんわ", "romaji": "denwa", "english": "telephone", "pos": "noun"},
    {"japanese": "じかん", "romaji": "jikan", "english": "time", "pos": "noun"},
    {"japanese": "おかね", "romaji": "okane", "english": "money", "pos": "noun"},
    {"japanese": "しごと", "romaji": "shigoto", "english": "work / job", "pos": "noun"},
    {"japanese": "くるま", "romaji": "kuruma", "english": "car", "pos": "noun"},
    {"japanese": "えき", "romaji": "eki", "english": "station", "pos": "noun"},
    {"japanese": "びょういん", "romaji": "byouin", "english": "hospital", "pos": "noun"},
    {"japanese": "みせ", "romaji": "mise", "english": "store / shop", "pos": "noun"},
    {"japanese": "ぎんこう", "romaji": "ginkou", "english": "bank", "pos": "noun"},
    {"japanese": "ゆうびんきょく", "romaji": "yuubinkyoku", "english": "post office", "pos": "noun"},
    {"japanese": "としょかん", "romaji": "toshokan", "english": "library", "pos": "noun"},
    {"japanese": "こうえん", "romaji": "kouen", "english": "park", "pos": "noun"},
    {"japanese": "でんしゃ", "romaji": "densha", "english": "train", "pos": "noun"},
    {"japanese": "バス", "romaji": "basu", "english": "bus", "pos": "noun"},
    {"japanese": "ひこうき", "romaji": "hikouki", "english": "airplane", "pos": "noun"},
    {"japanese": "からだ", "romaji": "karada", "english": "body", "pos": "noun"},
    {"japanese": "びょうき", "romaji": "byouki", "english": "illness", "pos": "noun"},
    {"japanese": "くすり", "romaji": "kusuri", "english": "medicine", "pos": "noun"},
    {"japanese": "てんき", "romaji": "tenki", "english": "weather", "pos": "noun"},
    {"japanese": "きた", "romaji": "kita", "english": "north", "pos": "noun"},
    {"japanese": "みなみ", "romaji": "minami", "english": "south", "pos": "noun"},
    {"japanese": "ひがし", "romaji": "higashi", "english": "east", "pos": "noun"},
    {"japanese": "にし", "romaji": "nishi", "english": "west", "pos": "noun"},
    {"japanese": "みぎ", "romaji": "migi", "english": "right", "pos": "noun"},
    {"japanese": "ひだり", "romaji": "hidari", "english": "left", "pos": "noun"},
    {"japanese": "うえ", "romaji": "ue", "english": "above / up", "pos": "noun"},
    {"japanese": "した", "romaji": "shita", "english": "below / down", "pos": "noun"},
    {"japanese": "まえ", "romaji": "mae", "english": "front / before", "pos": "noun"},
    {"japanese": "うしろ", "romaji": "ushiro", "english": "behind", "pos": "noun"},
    {"japanese": "なか", "romaji": "naka", "english": "inside", "pos": "noun"},
    {"japanese": "そと", "romaji": "soto", "english": "outside", "pos": "noun"},
    {"japanese": "となり", "romaji": "tonari", "english": "next to / neighbor", "pos": "noun"},
    {"japanese": "あいだ", "romaji": "aida", "english": "between", "pos": "noun"},
    {"japanese": "げつようび", "romaji": "getsuyoubi", "english": "Monday", "pos": "noun"},
    {"japanese": "かようび", "romaji": "kayoubi", "english": "Tuesday", "pos": "noun"},
    {"japanese": "すいようび", "romaji": "suiyoubi", "english": "Wednesday", "pos": "noun"},
    {"japanese": "もくようび", "romaji": "mokuyoubi", "english": "Thursday", "pos": "noun"},
    {"japanese": "きんようび", "romaji": "kinyoubi", "english": "Friday", "pos": "noun"},
    {"japanese": "どようび", "romaji": "doyoubi", "english": "Saturday", "pos": "noun"},
    {"japanese": "にちようび", "romaji": "nichiyoubi", "english": "Sunday", "pos": "noun"},
    {"japanese": "はる", "romaji": "haru", "english": "spring", "pos": "noun"},
    {"japanese": "なつ", "romaji": "natsu", "english": "summer", "pos": "noun"},
    {"japanese": "あき", "romaji": "aki", "english": "autumn", "pos": "noun"},
    {"japanese": "ふゆ", "romaji": "fuyu", "english": "winter", "pos": "noun"},
    {"japanese": "とても", "romaji": "totemo", "english": "very", "pos": "adverb"},
    {"japanese": "すこし", "romaji": "sukoshi", "english": "a little", "pos": "adverb"},
    {"japanese": "たくさん", "romaji": "takusan", "english": "many / a lot", "pos": "adverb"},
    {"japanese": "いつも", "romaji": "itsumo", "english": "always", "pos": "adverb"},
    {"japanese": "ときどき", "romaji": "tokidoki", "english": "sometimes", "pos": "adverb"},
    {"japanese": "よく", "romaji": "yoku", "english": "often / well", "pos": "adverb"},
    {"japanese": "まだ", "romaji": "mada", "english": "still / not yet", "pos": "adverb"},
    {"japanese": "もう", "romaji": "mou", "english": "already", "pos": "adverb"},
    {"japanese": "いっしょに", "romaji": "issho ni", "english": "together", "pos": "adverb"},
    {"japanese": "ゆっくり", "romaji": "yukkuri", "english": "slowly", "pos": "adverb"},
    {"japanese": "はい", "romaji": "hai", "english": "yes", "pos": "interjection"},
    {"japanese": "いいえ", "romaji": "iie", "english": "no", "pos": "interjection"},
    {"japanese": "おねがいします", "romaji": "onegai shimasu", "english": "please", "pos": "expression"},
    {"japanese": "だいじょうぶ", "romaji": "daijoubu", "english": "okay / all right", "pos": "na-adjective"},
    {"japanese": "ちょっと", "romaji": "chotto", "english": "a little / just a moment", "pos": "adverb"},
    {"japanese": "ぜんぶ", "romaji": "zenbu", "english": "all / everything", "pos": "noun"},
    {"japanese": "しかし", "romaji": "shikashi", "english": "however", "pos": "conjunction"},
    {"japanese": "でも", "romaji": "demo", "english": "but", "pos": "conjunction"},
    {"japanese": "そして", "romaji": "soshite", "english": "and then", "pos": "conjunction"},
    {"japanese": "それから", "romaji": "sorekara", "english": "after that", "pos": "conjunction"},
    {"japanese": "または", "romaji": "matawa", "english": "or", "pos": "conjunction"},
    {"japanese": "かぜ", "romaji": "kaze", "english": "wind / cold (illness)", "pos": "noun"},
    {"japanese": "ことし", "romaji": "kotoshi", "english": "this year", "pos": "noun"},
    {"japanese": "きょねん", "romaji": "kyonen", "english": "last year", "pos": "noun"},
    {"japanese": "らいねん", "romaji": "rainen", "english": "next year", "pos": "noun"},
    {"japanese": "こんしゅう", "romaji": "konshuu", "english": "this week", "pos": "noun"},
    {"japanese": "せんしゅう", "romaji": "senshuu", "english": "last week", "pos": "noun"},
    {"japanese": "らいしゅう", "romaji": "raishuu", "english": "next week", "pos": "noun"},
    {"japanese": "まいあさ", "romaji": "maiasa", "english": "every morning", "pos": "noun"},
    {"japanese": "まいばん", "romaji": "maiban", "english": "every night", "pos": "noun"},
    {"japanese": "りょこう", "romaji": "ryokou", "english": "travel / trip", "pos": "noun"},
    {"japanese": "しゃしん", "romaji": "shashin", "english": "photograph", "pos": "noun"},
    {"japanese": "うた", "romaji": "uta", "english": "song", "pos": "noun"},
]

# =============================================================================
# VOCABULARY LESSONS
# =============================================================================

VOCABULARY_LESSONS = [
    {
        "lesson_id": "vocab_01",
        "title": "Essential Greetings",
        "description": "Learn the most common Japanese greetings used every day.",
        "words_taught": ["ohayou gozaimasu", "konnichiwa", "konbanwa", "sayounara", "arigatou gozaimasu"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_02",
        "title": "Meeting People",
        "description": "Master self-introductions and polite meeting phrases.",
        "words_taught": ["hajimemashite", "yoroshiku onegai shimasu", "sumimasen", "ogenki desu ka"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_03",
        "title": "Numbers 1-20",
        "description": "Learn to count from one to twenty in Japanese.",
        "words_taught": ["ichi", "ni", "san", "yon", "go", "roku", "nana", "hachi", "kyuu", "juu"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_04",
        "title": "Family Members",
        "description": "Learn words for family relationships in Japanese.",
        "words_taught": ["kazoku", "okaasan", "otousan", "oniisan", "oneesan", "otouto", "imouto"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_05",
        "title": "Food and Drink",
        "description": "Essential vocabulary for eating and drinking.",
        "words_taught": ["gohan", "pan", "niku", "sakana", "mizu", "ocha", "itadakimasu"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_06",
        "title": "Animals",
        "description": "Learn the names of common animals.",
        "words_taught": ["inu", "neko", "tori", "uma", "ushi", "buta", "sakana"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_07",
        "title": "Body Parts",
        "description": "Learn vocabulary for parts of the body.",
        "words_taught": ["atama", "kao", "me", "mimi", "kuchi", "te", "ashi"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_08",
        "title": "Time and Days",
        "description": "Learn days of the week, seasons, and time words.",
        "words_taught": ["kyou", "ashita", "kinou", "getsuyoubi", "haru", "natsu", "aki", "fuyu"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_09",
        "title": "Places Around Town",
        "description": "Vocabulary for navigating a Japanese town.",
        "words_taught": ["eki", "gakkou", "byouin", "ginkou", "mise", "kouen", "toshokan"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_10",
        "title": "Essential Verbs",
        "description": "Learn the most important action words.",
        "words_taught": ["taberu", "nomu", "miru", "iku", "kuru", "suru", "aru", "iru"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_11",
        "title": "Describing Things",
        "description": "Common adjectives for describing the world around you.",
        "words_taught": ["ookii", "chiisai", "takai", "yasui", "oishii", "tanoshii", "kirei", "genki"],
        "monument_id": 3,
    },
    {
        "lesson_id": "vocab_12",
        "title": "Counters and Counting Objects",
        "description": "Learn Japanese counting systems and counters.",
        "words_taught": ["hitotsu", "futatsu", "hitori", "futari", "ippon", "ichimai", "issatsu"],
        "monument_id": 3,
    },
]
